- shark_turbine/ops/iree.py
- shark_turbine/runtime/device.py
- shark_turbine/runtime/op_reg/base.py
- shark_turbine/runtime/op_reg/compiler.py
- tests/runtime/device_test.py
* Adds a custom IREE "_test_add" op which exercises actual code generation.
* Reworks the device management layer to:
* Initialize our `Device` wrapper to maintain the correspondence between IREE HalDevice and PyTorch device.
* Annotated Device with dlpack_device_type_code.
* Detects whether the Torch device is for real-CUDA or AMDGPU/HIP CUDA and interfaces to the outside world correctly based on this.
* Auto-detects the AMDGPU chip and the CUDA SM version and arranges for the JIT compiler to use that.
* Dynamically enables custom kernel registration for CUDA if it is available.
Limitations (for now):
* IREE's dlpack interop only supports contiguous tensors. Lifting this requires further interfacing with the compiler to specialize on different strided layouts.
* Device synchronization is …
> Add device bridge support for HIP and CUDA.

- tests/aot/params_test.py
Fix was similar to https://github.com/iree-org/iree/commit/11d22592941b934d47289fe03441a3ed07f14f08
Once a temporary file is opened on Windows, it can't be reopened unless some extra conditions are met. From https://docs.python.org/3/library/tempfile.html:
> Opening the temporary file again by its name while it is still open works as follows:
> * On POSIX the file can always be opened again.
> * On Windows, make sure that at least one of the following conditions are fulfilled:
>     * _delete_ is false
>     * additional open shares delete access (e.g. by calling [os.open()](https://docs.python.org/3/library/os.html#os.open) with the flag O_TEMPORARY)
>    * delete is true but delete_on_close is false. Note, that in this case the additional opens that do not share delete access (e.g. …
> Fix params_test on Windows.

- requirements.txt
- shark_turbine/aot/params.py
- shark_turbine/runtime/__init__.py
- shark_turbine/runtime/device.py
- shark_turbine/runtime/launch.py
- shark_turbine/runtime/op_reg/compiler.py
- tests/runtime/launch_test.py
This uses much of the plumbing of the custom ops workflow but is geared for larger scale integrations. Whereas the custom op system is optimized for things more "kernel" sized, focusing on specialization and JIT compilation of variants, this workflow is geared towards integrating entire programs (either from VMFB or JIT compiled for the device in use on the fly) as a Torch callable.
Usage for bring-your-own-VMFB:
```
launch = Launchable.from_vm_module(lambda device: VmModule.mmap(device.vm_instance, "foo.vmfb"))
result = launch(tensor1, tensor2)
```
Usage for JIT compiling:
```
launch = Launchable.jit_compile(MLIR_ASM)
result = launch(tensor1, tensor2)
```
In the first case, it is the caller's responsibility to produce a VMFB that is valid for the given device. In the JIT case, …
> Add a Launchable class for directly running IREE modules on PyTorch devices.

- .github/workflows/ci.yaml
- .github/workflows/test_shark.yml
- shark_turbine/transforms/quantization/mm_group_quant.py
Must feed in output shape to the tensor.expand_shape op after an upstream change. This allows us to patch IR for quantized llama2.
> Update mm_group_quant.py template for MLIR upstream change

- shark_turbine/aot/params.py
- tests/aot/params_test.py
> Add workaround for roundtripping 0d tensors in parameter archive.

- .github/workflows/test_models.yml
- .github/workflows/test_shark.yml
This commit makes the necessary changes to both the workflows to get the CI working properly. The SHARK workflow file is temporarily using a branch that I created in nod-ai/SHARK to resolve some versioning issues. I will land there and update this back to use the main branch once that happens.
> CI Fixes for test_models and SHARK testing

- shark_turbine/aot/exporter.py
- tests/aot/non_strict_export_test.py
This exposes the option described in https://pytorch.org/tutorials/intermediate/torch_export_tutorial.html#non-strict-export to the user. This leads to way less graph breaks when using the export API. This is set to False by default because it is still experimental.
Fixes https://github.com/iree-org/iree-turbine/issues/12
> [Export] Expose non strict mode for user

- examples/runtime_torture/README.md
- examples/runtime_torture/launchable_torture.py
- shark_turbine/runtime/launch.py
Previously we've only had unit tests and live use. Adding some systematic examples aimed at stressing the torch<->iree runtime layer.
Also fixed an enum issue that is at IREE head (fallout from the nanobind update).
CPU results:
```
reference total time: 4570.794267579913ms
tensor([[0.1936, 0.1991, 0.1913,  ..., 0.1971, 0.1890, 0.1886],
[0.1936, 0.1991, 0.1913,  ..., 0.1971, 0.1890, 0.1886],
[0.1935, 0.1991, 0.1912,  ..., 0.1971, 0.1888, 0.1885],
...,
[0.1935, 0.1991, 0.1912,  ..., 0.1971, 0.1890, 0.1885],
[0.1936, 0.1991, 0.1912,  ..., 0.1971, 0.1890, 0.1886],
[0.1935, 0.1990, 0.1912,  ..., 0.1970, 0.1888, 0.1885]],
dtype=torch.float16)
*** moved inputs to device
turbine total time: 128.97808896377683ms
tensor([[0.1936, 0.1991, 0.1913,  ..., 0.1971, 0.1890, 0.1886],
[0.1936, 0.1991, …
```
> Starts adding some systematic runtime torture tests.

- shark_turbine/dynamo/decompositions.py
this op will otherwise fail in torch-mlir due to shape information not propagating
> add decomposition for linspace.Tensor_Tensor

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/tracing.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_gemm_test.py
This adds the expansion of the original program depending on workgroup and hardware constraints.
The exact semantics can be seen well in the new [tests](https://github.com/iree-org/iree-turbine/blob/dedd438641072ac9e5f47dc60212a9306de55a00/lit_tests/kernel/wave/expansion.py).
Additionally, this introduces:
- `HardwareConstraint` that specifies the number of waves per block, number of threads per wave and mma instruction sizes. 
- New custom nodes for:
`Output`, `IterArg`
- Some new convenience features like updating the args of a node through the custom interface. (Ideally this would be accomplished through intercepting dataclass setters, but that interferes with the tracing and I did not yet find a workaround.)
In particular the handling of iterArgs should be improved in follow-up PRs. …
> Add TKW graph expansion

- shark_turbine/kernel/wave/wave_sim.py
- tests/kernel/wave/wave_sim_test.py
Software simulator for `tk.wave` kernels. It doesn't do any actual compilation or tracing and just executes kernel entirely inside python interpreter, so you can use `print`, python debugger, etc.
No tiling or distribution is done, `tkw.reduction` will always execute a single iteration (as if tile size was bigger than iteration size).
All data (i.e. `Register`) inside kernel is represented using `torch.tensor`.
Currently supported ops:
* `Register`
* `read`
* `write`
* `mma`
* `reduction`
> [WIP] TK.wave simulator

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- shark_turbine/kernel/_support/tracing.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/expansion.py
- tests/kernel/wave/constraints_test.py
This PR adds a tiling constraint primitive to the language. This is used to represent constraints on how a dimension is to be tiled. In contrast to the workgroup constraints, dimensions with a tiling constraint on them are not distributed and materialized to sequential loops.
This PR also adds support for a third workgroup dimension and deduces the mapping of user dimensions to MMA dimensions based on the operands of the tkw.mma operator.
> Add TilingConstraint to represent non-distributed tiled loops

- shark_turbine/kernel/wave/constraints.py
This PR describes the vector_shapes keyword and updates its type to IndexSymbol -> int, as it is a map from tensor dimensions to tile sizes.
> Add description of vector_shapes keyword in hardware constraint

- tests/kernel/wave/wave_sim_test.py
As I'm using `torch.tensor` in simulator, all elementwise ops and broadcasting should work out of the box.
> Add elementwise and broadcast simulator tests

- lit_tests/kernel/wave/expansion.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/distribution_symbols.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/indexing.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/constraints_test.py
- tests/kernel/wave/wave_gemm_test.py
This primary purpose of this PR is to annotate nodes with their access patterns based on the workgroup, tiling and MMA constraints. This is accomplished prior to expansion and propagates through expansion to the expanded nodes.
> Add indexing to nodes

- .github/workflows/ci.yaml
Pass `-v` option to lit to enable verbose output so we can actually see what failed exactly.
> Make CI lit verbose

- shark_turbine/kernel/ops/wave_ops.py
Do not print `None` args on `CustomOp` to reduce churn when adding new optional args.
> Do not print None args

- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/wave.py
This avoids an possible namespace collision
with user defined variables. Also does minor
refactors.
> Prefix induction variables with $

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/compiler/kernel_codegen.py
- shark_turbine/kernel/compiler/utils.py
- tests/kernel/compiler/utils_test.py
When the static shape information is available,
we use a strided memref type with a dynamic offset for integration with iree.
> Add strided and dynamic offset to memref type

- .github/workflows/ci.yaml
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/tracing.py
- shark_turbine/kernel/lang/__init__.py
- shark_turbine/kernel/lang/wave_types.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/__init__.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/wave.py
- shark_turbine/kernel/wave/wave_sim.py
- tests/kernel/wave/wave_sim_test.py
Add `mapping` argument to `read` and `write` ops and add support to the simulator.
* Add `IndexMapping` class which describes how to map between 2 sets of indices. Mapping consists of set of iterators and input/output dicts, which describe, how to map symbolic dimension to the specific iterator. Mapping is similar to `linalg.generic` index maps, where it's iterators corresponds to linalg `parallel` iterator. The difference is that we are binding iterator to dimensions symbols instead of dim index. E.g. if we have mapping like this:
```
i = tkw.IndexMapping.iterator(0)
j = tkw.IndexMapping.iterator(1)
mapping = tkw.IndexMapping(
num_iterators=2, inputs={N: i, M: j}, outputs={N: i, M: j}
)
```
If the input array has shape `[N, M]`, we will copy a contiguous slice, but for the input shape …
> Wave sim mapping support and igemm kernel

- pytorch-cpu-requirements.txt
- pytorch-rocm-requirements.txt
- shark_turbine/aot/builtins/jittable.py
- shark_turbine/aot/exporter.py
- shark_turbine/aot/params.py
- shark_turbine/dynamo/tensor.py
- tests/aot/functionalize_test.py
- tests/aot/jittable_test.py
- tests/aot/non_strict_export_test.py
- tests/dynamo/importer_dynamic_test.py
This commit makes the necessary changes to adapt to the new torch 2.4 API. The main change here is regarding the exporting of dynamic shape constraints: https://github.com/pytorch/pytorch/commit/342e7929b804ec56121e82e92d6a199b549c38b1.
Also changed the test for strict export for something that still holds.
> Adapt to torch 2.4 API

- .github/workflows/test_shark.yml
Torch versioning is off and outdated, leading to errors in that setup_venv.sh script in SHARK repo
> Sync with SHARK-Turbine test-shark CI

- .github/workflows/ci.yaml
- iree-requirements-ci.txt
- shark_turbine/ops/iree.py
- shark_turbine/runtime/op_reg/base.py
- tests/ops/iree_test.py
This exposes IREE's multi-device capabilities to PyTorch programs, allowing them to transfer parts of the computation to other devices. This will be used as part of the sharding work in sharktank to do auto placement of sharded tensors (i.e. across GPU devices, etc). But it is also available for heterogenous/ad-hoc offload to other devices (GPU slices, CPU slices, NPU, etc).
Since this is the first op we have that has different eager vs graph mode semantics, add a new CustomOp.eager_execute() hook which allows the eager execution semantics to be specified separately from graph compilation. Since these local device transfers are only meaningful within an IREE program, they are no-ops during eager execution.
(requires a WIP branch on IREE)
> Add ops.iree.transfer_to_logical_device() custom op.

- CONTRIBUTING.md
IREE was moved out of OpenXLA into the Linux Foundation (LF AI & Data): https://lfaidata.foundation/blog/2024/05/23/announcing-iree-a-new-initiative-for-machine-learning-deployment/ Therefore, switching the code of conduct to
https://lfprojects.org/policies/code-of-conduct/.
> Switch code of conduct from OpenXLA to LF Projects

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/wave/codegen.py
Use original `memory` symbolic shape to determine dimensions access order.
> [TK] Fix gather indices

- lit_tests/kernel/wave/promotion.py
- shark_turbine/kernel/wave/promotion.py
- shark_turbine/kernel/wave/wave.py
This PR adds promotion to shared memory and hoisting of shared memory allocs to wave. If a placeholder is marked with its address space as SHARED_MEMORY, the compiler will introduce the appropriate promotion.
> Add automatic promotion and hoisting of placeholders

- .gitignore
- lit_tests/kernel/wave/expansion.py
- shark_turbine/kernel/wave/visualization.py
- tests/kernel/wave/visualization_test.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds graphviz-based functionality to
visualize fx graphs. This is a useful graphical tool for debugging graph transformations.
> Add function to visualize fx graphs

- lit_tests/kernel/wave/barriers.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/barriers.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/expansion.py
This PR introduces a shared memory barrier op that can be used to to introduce barriers between writes and reads to shared memory. We use the write_dependency field of read nodes as well as the node indices to determine whether to insert a barrier. Also, we try to re-use barriers to minimize the total number of barriers.
> Add shared memory barriers for RAW dependencies

- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/tracing.py
- shark_turbine/kernel/wave/utils.py
This PR moves the common run and print_trace
utilities to the utils file so they do not
need to duplicated in every test.
> Refactor run and print_trace methods

- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_e2e_test.py
Example config
```python
config = {
"backend": "rocm",
"device": "hip",
"target": "gfx942",
"benchmark": True,
"benchmark_batch_size": 100,
"benchmark_repetitions": 3,
"benchmark_results_file": "out.json",
}
```
Example output:
```
[
[
"BM_isolated_benchmark/process_time/real_time",
"0.036 ms",
"0.080 ms",
"19313",
"items_per_second=27.6075k/s"
],
[
"BM_isolated_benchmark/process_time/real_time",
"0.036 ms",
"0.081 ms",
"19313",
"items_per_second=27.4817k/s"
],
[
"BM_isolated_benchmark/process_time/real_time",
"0.036 ms",
"0.081 ms",
"19313",
"items_per_second=27.5867k/s"
],
[
"BM_isolated_benchmark/process_time/real_time_mean",
"0.036 ms",
"0.081 ms",
"3",
"items_per_second=27.5586k/s"
],
[
"BM_isolated_benchmark/process_time/real_time_median",
"0.036 ms",
"0.081 ms",
"3",
```
> [TK] Some basic APIs for benchmarking

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/codegen.py
This PR introduces ops required to implement Flash Attention
1. Create new template to make adding unary/binary ops easier
2. Add symbolic type propagation for BinaryPyOp and UnaryPyOp (to work with mapping codegen)
3. Implemented elementwise ops needed for FA2.
> [TKW] Implement various ops required for FA

- shark_turbine/kernel/wave/visualization.py
Previously, nodes were identified by their id(). This is unstable and would result in different files being generated for the same input. We fix this by using our manually specified ordering for the nodes.
> Use more stable ordering of nodes during visualization

- iree-requirements.txt
We had experience of tests suddenly failing, we should make iree-compiler/iree-runtime pip package updates more delibrate.
> [dep] pin IREE versions

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- shark_turbine/kernel/wave/expansion.py
* Thread offset for non-fastest dimension must be 1 instead of 0 so indexing actually takes thread_id into account
* Change `type.symbolic_shape` to `indexing_dims`, they should be the same for normal read/writes, but with presence of mapping dims must be extracted from mapping and `indexing_dims` is already doing this.
> [TKW] Fix thread offset on non-fastest dimension

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/decompose_reduce_ops.py
- shark_turbine/kernel/wave/register_analysis.py
- tests/kernel/wave/wave_e2e_test.py
In this PR, we add 3 things:
1. Define Interface Op
2. Reduction max op
3. elementwise maximum op
Define interface op is created to generate new subclass op that can
derive from base interface class. this is useful for custom TK ops that
has very similar properties such as "sum" and "max" S.T we can reuse
code as much as possible.
> [TKW] Implement define interface op and tk.max

- shark_turbine/kernel/wave/iree_utils.py
- shark_turbine/kernel/wave/utils.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds utils to generate an iree reference
mmt kernel that can be compiled and run to
obtain a golden output for comparison. Compared
to the torch output, the advantage of this output
is that it can be matched exactly and makes for
an easier comparison target.
> Add iree_ref for gemm functionality test

- shark_turbine/aot/builtins/jittable.py
- shark_turbine/aot/support/procedural/exported_program.py
In the upstream FxImporter, an `info` arg was added to resolve_literal. Adding it to the hooks here (without use) so that iree-turbine is forward/backward compatible with respect to this change.
See https://github.com/llvm/torch-mlir/pull/3688
> Adapt to API break where resolve_literal takes an InputInfo arg.

- shark_turbine/aot/fx_programs.py
For large model strictness requires loading the contents of each tensor. Disabling allows extremely large models to not require massive amounts of ram.
> Enable disabling strictness

- shark_turbine/kernel/wave/scheduling/graph_utils.py
- shark_turbine/kernel/wave/scheduling/modulo_scheduling.py
- tests/kernel/wave/scheduling_test.py
This PR adds a function that modifies Floyd-Warshall to compute the longest paths in a graph with
cycles with the assumption that the cycles don't
have positive weights.
> Add all pairs longest paths utility

- lit_tests/kernel/wave/index_sequence_analysis.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/index_sequence_analysis.py
- shark_turbine/kernel/wave/utils.py
This PR modifies the linear index sequence when using vector shapes to use the absolute stride instead of the relative stride.
> Use absolute stride when computing index sequence for vector shapes

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/index_sequence_analysis.py
- shark_turbine/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/wave/shared_memory_indexing.py
- shark_turbine/kernel/wave/wave.py
This PR introduces a new function to apply shared
memory indexing corrections. Previously, this was being done as part of post expansion. With the new PR, we look at the entire graph holistically and apply indexing changes to reads from shared memory.
> Add separate function to apply shared memory indexing

- tests/kernel/wave/wave_gemm_test.py
`assert_allclose` will actually show you how many elements mismatched and the relative/absolute difference.
> Use `assert_allclose` in gemm test

- shark_turbine/kernel/ops/wave_ops.py
Previously, the computation of iter_args and
captured_vars was based on ordering which was brittle. We modify it to use the type information of the nodes.
> Fix computation of iter_args and captured_vars

- pytorch-cpu-requirements.txt
- pytorch-rocm-requirements.txt
Recent torch 2.5 versions failing with `ImportError: cannot import name 'dynamic_dim' from 'torch.export'`, pin torch version `<2.5.0` for now, until proper fix is ready https://github.com/iree-org/iree-turbine/pull/145
> Pin torch version until deprecated functionality is fixed

- pytorch-rocm-requirements.txt
Revert `pytorch-rocm-requirements.txt` as they doesn't provide 2.4 version.
Version which works for me locally is `2.5.0.dev20240802+rocm6.0`.
> Revert rocm-requirements.txt

- shark_turbine/kernel/lang/global_symbols.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/scheduling/__init__.py
- shark_turbine/kernel/wave/scheduling/graph_utils.py
- shark_turbine/kernel/wave/scheduling/modulo_scheduling.py
- shark_turbine/kernel/wave/scheduling/resources.py
- shark_turbine/kernel/wave/scheduling/schedule.py
- shark_turbine/kernel/wave/utils.py
- shark_turbine/kernel/wave/visualization.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/scheduling_test.py
This PR adds the code to schedule tkw gemms. We
have to construct edges for the modulo scheduler
and define resources that are available for the
scheduler. These resources are tunable.
> Add code to schedule GEMMs

- tests/kernel/wave/.gitignore
- tests/kernel/wave/wave_gemm_test.py
This is a QOL developer option to easily inspect the generated code. Enabled with `WAVE_DUMP_MLIR=1`, the generated gemms get saved to the test dir.
> [TKW] Add test option to dump generated gemm mlir

- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/expansion.py
This PR modifies the insertion point for iter args to ensure that the iter args are in the same order as the init args and outputs. This simplifies the mapping between init args, iter args and outputs.
> Reorder iter args to match ordering of init args and outputs

- shark_turbine/aot/support/procedural/exported_program.py
- tests/aot/globals_test.py
Fixes iree-org/iree-turbine#85
PR based on the work of @maxbartel 
Requires changes in torch-mlir: [llvm/torch-mlir/#3688](https://github.com/llvm/torch-mlir/pull/3688)
Adds the mutable modifier to a global buffer and lifts said buffer to a global if there is a store-producer node associated with it.
>  [ExportedProgram] Add mutable attribute to buffer

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/expansion.py
This PR introduces changes to handle elementwise or general arithmetic operations after we did some tiled-loop-reduction ("Reduction") operation.
The main problem with the current stack is indexing_dims information for Reduction relies on the user. This would work if it's user/consumer is tkw.write, but in other cases such as BinaryPyOp or UnaryPyOp, it will lack such information.
To make matters worst BinaryPyOp/UnaryPyOp depends on it's src/producer for indexing dim, while Reduction op depends on it's dst/consumer for its' indexing dim information. This would ended up causing infinite loop between UnaryPyOp/BinaryPyOp <-> Reduction.
This PR fixes the indexing dimension logic Reduction and GetResult (required for expanded Reduction) to be based on it's reduction axis(for Reduction) and …
> [TKW] Fix indexing of Reduction and GetResult to enable post-tile op.

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/index_sequence_analysis.py
- shark_turbine/kernel/wave/utils.py
This PR removes the need for propagating indices using
post expansion. The new approach propagates the MMA
indices to the MMA dimensions of all tensors (rather
than just MMA nodes) and then specializes them depending
on whether they lie within the backward slices of the
LHS and RHS or forward slices of the ACC.
> Get GEMMs working without minimize_global_loads

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/utils.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_e2e_test.py
The main motivation behind this PR is to enable multiple induction variable/iterArg on the same tiled "Reduction" loop. To enable above we did a couple things:
1. Enable lowering/expansion on `operator.getitem` (the op that extract multiple results in python i.e `res0, res1 = fn`) by templating it on`GetResult(CustomOp)` since they have the same args and interface and can reuse most of the indexing/expansion helper.
2. Introduce `res_idx`, a variable to represent which result index of an op we are referring to, during expansion and context map. This is useful for ops that has more than one results / variables as outputs.
3. bug fix in expand_reduction, where we hoist out iterating and expanding of `reduction.init_args` out of the loop that iterates and expands over the …
>  [TKW] Implement support for multiple iter args on Reduction

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/_support/indexing.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/utils.py
Instead of generating individual element comparisons and doing `vector.insertelement` generate the whole mask using vector ops.
Add support for vector codegen when generating MLIR IR from sympy expressions. Add method `IndexingContext.iota` to generate special symbols which map to `(1,2 ... n-1)` vec expressions. `gen_sympy_index` will start to generate vector ops when encountering such symbols, inserting proper `splat`'s between scalar vals when necessary.
> [TKW] Rework vector mask generation

- shark_turbine/aot/compiled_module.py
- shark_turbine/aot/exporter.py
- shark_turbine/aot/support/ir_utils.py
- shark_turbine/aot/support/procedural/exported_program.py
- tests/aot/dynamic_shape_export_test.py
* Adds an option to `aot.export(import_symbolic_shape_expressions=True)` to enable emission of torch-mlir symbolic shape constraints. This is currently set to False until IREE is ready to ingest these by default.
Rough sequence of work in IREE proper:
* Custom lowering of `torch.symbolic_int` and `torch.bind_symbolic_shape` ops to IREE util "assume" ops. Note that we are only planning to lower "terminal" bindings (basically function arguments and a couple of other such categories).
* Canonicalizations to ensure that assume equalities are == 0 (versus the native form from torch where they assume a non zero equality).
* Fusion will clone corresponding bindings on dependent dims into dispatch regions.
* Existing linalg shape analysis extended and queryable by codegen.
> Enable import_symbolic_shape_expressions in the FxImporter.

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/compiler/dispatch_codegen.py
- shark_turbine/kernel/compiler/host_codegen.py
- shark_turbine/kernel/compiler/kernel_codegen.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/utils.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_e2e_test.py
This PR adds support for dynamic dimensions in the
kernels. The user specifies the dynamic dimensions
by
- Not adding them to the hyperparameter dictionary
- Explicitly specifying them with the dynamic_symbols kwarg
and the dynamic_symbols_mapping kwarg to specify which
values to use for the dynamic dims at runtime
This PR does not modify the codegen and so incorrect or
unsupported values for the dynamic dims will result
in incorrect results. (garbage in -> garbage out)
> Add support for dynamic dims

- .github/workflows/ci.yaml
- .github/workflows/perf.yaml
- .github/workflows/test_build_release.yml
Our tests are flaky, `fail-fast: false` won't allow failing builds abort other.
> Set `fail-fast: false`

- shark_turbine/kernel/wave/utils.py
This PR adds a flag to dump intermediates which include .ll and .s files to see what instructions were
generated.
> Add ability to dump intermediates

- .github/workflows/ci-tk.yaml
- .github/workflows/ci.yaml
- .github/workflows/perf.yaml
* Main CI is flaky, add a separate pipeline, which tests only TK as temp solution
* Make `pytest` output more verbose
* Remove unnecessary stuff from perf pipeline
> Split TK CI from main CI

- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
- shark_turbine/kernel/wave/promotion.py
This PR adds padding to shared memory allocations
to minimize bank conflicts.
> Add padding to reduce shared memory bank conflicts

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/scheduling/__init__.py
- iree/turbine/kernel/wave/scheduling/loop_reconstruction.py
- iree/turbine/kernel/wave/scheduling/resources.py
- iree/turbine/kernel/wave/scheduling/schedule.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds op for scheduling barriers and
scheduling group barriers. These are placed
after every cycle in the kernel.
> Add support for scheduling barriers

- iree/turbine/ops/iree.py
This solves the problem in https://github.com/iree-org/iree/issues/18283
The issue is that we generate cast to/from dynamic tensors that later lowering in IREE chocks on it. My assumption is that it should be able to digest this IR since it is of the form.
```mlir
%2 = torch_c.to_builtin_tensor %arg0 : !torch.vtensor<[2,3,11,13],f32> -> tensor<2x3x11x13xf32>
%cast = tensor.cast %2 : tensor<2x3x11x13xf32> to tensor<?x?x?x?xf32>
%c0 = arith.constant 0 : index
%dim = tensor.dim %cast, %c0 : tensor<?x?x?x?xf32>
%c1 = arith.constant 1 : index
%dim_0 = tensor.dim %cast, %c1 : tensor<?x?x?x?xf32>
%c2 = arith.constant 2 : index
%dim_1 = tensor.dim %cast, %c2 : tensor<?x?x?x?xf32>
%c3 = arith.constant 3 : index
%dim_2 = tensor.dim %cast, %c3 : tensor<?x?x?x?xf32>
%3 = flow.tensor.transfer %cast : …
```
> Enforce static dimensions in generation of flow.tensor.transfer

- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/iree_utils.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds support for batch dimensions.
They can be specified in the vector_shapes dict
with a shape of 0 with a corresponding workgroup
constraint. This specifies that we want to distribute the batch dim among workgroups, but not among threads.
> Add support for batch matmuls

- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
Previously, we could end generating dynamic indices both for the gather `start_indices` and `offsets_vec` which is suboptimal.
Now, detect if we need dynamic `offsets_vec`, and generate `start_indices` as 0 in this case, encoding entire index calculation in `offsets_vec`.
> [TKW] Refactor gather indices generation

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/casting.py
- tests/kernel/wave/wave_e2e_test.py
This PR adds an op that can cast between
integer and float types of different bitwidths.
> Add op to cast between dtypes

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/decompose_reduce_ops.py
- iree/turbine/kernel/wave/thread_shape_analysis.py
- lit_tests/kernel/wave/codegen.py
This PR add supports for doing accumulate on non-induction variables. For most part our stack already supports this, but we'd need to fix reduction symbolic shape which used to be just the input shape to input shape - reduction dim. Without this our thread shape analysis wouldn't be able to handle broadcasting of reduced op properly.
To support the above, we also introduce `Extract` op in addition to the existing `ExtractSlice` to fix the shape types. Specifically, ExtractSlice follow upstream's semantic where we just slice but do not reduce any dimensions. For the ReduceOp case, specifically the local reduction, we'd want it to have a reducing semantic on the fastest dimension.
Additionally, we also add a propagation of our resolution for thread shape. This is helpful in the test we …
> [TKW] Fix types, shapes and propagate resolved indexing 

- pytorch-rocm-requirements.txt
The CPU requirements restrict torch to a version < 2.5.0, whereas the ROCm requirements did not so far. The current iree-turbine is incompatible with torch 2.5.0 as `torch.export.dynamic_dim()` was removed with pytorch/pytorch@b454c51. Version 2.4 releases for ROCm 6.0 are available via a different channel, changing that accordingly.
> Restrict to torch < 2.5.0 and change channel

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/minimize_global_loads.py
- iree/turbine/kernel/wave/shared_memory_indexing.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
Add a pass which adjusts shared mem reads/writes and MMA indices to never had to partial accesses. This is need to remove masking ops on shared mem.
Also, update `minimize_global_loads.py` to use ceildiv instead if floor div in case of unaligned sizes.
> [TKW] Make shared mem read/writes using non masked ops

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/scheduling_test.py
- tests/kernel/wave/visualization_test.py
This PR separates the setting of indices pre-
and post-expansion from expansion itself. This
separation of concerns should make the overall
design more modular.
> Move index setting outside of expansion

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/thread_shape_analysis.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/minimize_global_loads.py
In this PR, we add support to propagate indexing, expansion, and thread shape information from IterArg/induction variable of Reduction loop to it's user outside the loop. 
This is important to enable for example having two induction variables in a reduction loop with different layout/index, and we'd want to do a binaryOp on them before writing them out. We'd need to figure if for example it'd need a broadcast or not. That won't be possible if we do not propagate this information from IterArg to outside/GetResult and it's use-def chain.
> [TKW] Propagate GetResult/IterArg of Reductions out for expansion and thread shape

- iree/turbine/aot/compiled_module.py
- iree/turbine/aot/exporter.py
- iree/turbine/aot/fx_programs.py
- iree/turbine/aot/support/ir_utils.py
- iree/turbine/aot/support/procedural/exported_program.py
- iree/turbine/aot/support/procedural/tracer.py
- iree/turbine/aot/tensor_traits.py
- iree/turbine/support/ir_imports.py
- tests/aot/args_test.py
- tests/aot/compiled_exported_program_test.py
- tests/aot/fx_programs_test.py
- tests/aot/fx_programs_test_device.py
We don't have support for providing device affinities for function arguments, which need to end up as MLIR function argument attributes.
This change adds a class DeviceAffinity and provides the ability to supply affinities when exporting Torch functions/modules or when tracing in IREE-Trubine itself.
> Add device affinities for arguments in AOT

- iree/turbine/ops/iree.py
- tests/ops/iree_test.py
Currently eager and generate don't have the same semantics. Generate would create a new value while in eager we return the same tensor.
It is desirable to have the same behavior in both paths, this will allow us to catch in-place errors on the torch level and not during IREE execution.
The only downside is that during eager it will be slower. This is far less of headache.
> Make transfer_to_logical_device copy the tensor during eager execution

- iree/turbine/aot/support/ir_utils.py
- iree/turbine/aot/tensor_traits.py
- tests/aot/params_test.py
Exported globals can now be parked to belong to a specific device. This works with sharding tooling to ensure globals are not misassigned to the default affinity device
> Add `DeviceTensorTrait` to export annotations

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/iree_utils.py
- iree/turbine/kernel/wave/thread_shape_analysis.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- tests/kernel/wave/wave_attention_test.py
This PR adds support for chained matmuls. In
order to do this, we implement the following
- Support for op-specific vector_shapes
- Support for op-specific dim expansions (reduction
dims of mmas will now always have chained expansions,
even if they are not the induction variable of
reduction ops)
- Adds a permute operator
- Adds anchor and vector_shapes to each op
- Adds reduction_dim to MMA ops
> Add support for chained matmuls

- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/utils.py
This PR address comments from a previous PR, namely
- now only one pass through the graph is required to set the vector shapes and index
- the MMA index is now specified using an enum, the MMAOperand, which allows for better verification
> Minor cleanups and refactoring

- iree/turbine/kernel/wave/decompose_reduce_ops.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
This PR modifies the shuffle op global reduction so that it determines the number of threads and the stride between them from the reduction source's index.
> Modify the shuffle op to use information from the index sequence

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/expansion.py
- lit_tests/kernel/wave/expansion.py
In flash attention, we need to enable non direct acc matmul, and also expansion of reduceOp in reduction dimension. The former is needed in FA since we are applying some scaling to the acc of second MMA before feeding it in. The second case is required in FA because ReduceOp/MaxOp is in the backward slice of second MMA's LHS, which would require it to be expanded in K2/reduction dim as well.
> [TKW] Teach expansion to handle non direct acc and ReduceOp on reduction dim.

- iree/turbine/kernel/ops/wave_ops.py
- tests/kernel/wave/wave_attention_test.py
Most of the time in GPU programming, we would only materialize "transposes"/"permutes" of data during reads and writes. When doing transposes/permutations of data in GPU registers, it is most of the time free/no-op, since threads will still own the same data but just symbolically different.
> [TKW] Fix indexing of permute to enable attention

- tests/kernel/wave/wave_attention_test.py
Turns out ordering of mapping matters
> [TKW] Fix attention kernel to do non transposed output

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/iree_utils.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- tests/kernel/wave/wave_attention_test.py
This PR adds support for expanding operators
with varying vector shapes, specifically for the
MMA case where either the same dimension has different vector shapes in different mmas or if different instructions are being used.
The idea is to insert a reshape operator whenever such a shape mismatch is discovered.  The reshape operator lowers to an extract or concatenate operation, depending on the context.
> Add support for varying vector shapes

- iree/turbine/kernel/wave/decompose_reduce_ops.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/thread_shape_analysis.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/wave_attention_test.py
This PR adds support for the 32x32x8 intrinsic in
attention. This should allow for a wider search space when tuning attention.
In order to do so, the following changes were required:
- Add reshape as an anchor op in thread shape analysis, primarily to block the backward propagation of thread shapes from the MMA operands
- Modify assignment of anchor ops to take indexing dims into account
> Add support for more intrinsics in attention

- iree/turbine/ops/iree.py
- iree/turbine/support/debugging.py
- tests/ops/iree_test.py
We don't trace in eager mode in `ops.iree.trace_tensor`.
This adds the ability to set a tensor trace callback with a default implementation that records the tensor to a npy file.
> Add tensor tracing in eager mode

- iree-requirements-ci.txt
- iree/turbine/kernel/wave/codegen.py
This release was just promoted to stable: https://github.com/iree-org/iree/releases/tag/candidate-20241104.1068. As we align the versions across projects (https://github.com/iree-org/iree/issues/18938), we should aim to use stable versions or at least test nightly versions with care.
> Bump iree-requirements-ci.txt to the latest stable release.

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/type_inference.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/scheduling_test.py
- tests/kernel/wave/type_inference_test.py
- tests/kernel/wave/visualization_test.py
This PR adds a type inference pass to wave. Previously, the types were infered by looking up types from neighbors resulting in inefficient type inference.
Instead, we now introduce a pass that infers the types for all operators in the graph and the inferred type is then stores in the node. New nodes that are constructed in downstream passes are responsible for annotating types for the new operators.
> Add type inference

- .github/workflows/test_build_release.yml
- build_tools/build_release.py
- docs/releasing.md
- setup.py
- version_info.json
The `docs/releasing.md` file was first introduced next to the `build_release.py` script in https://github.com/nod-ai/SHARK-ModelDev/pull/605. I don't see that file in this repository (iree-org/iree-turbine) though, despite https://github.com/nod-ai/SHARK-ModelDev/pull/655 claiming that it had been upstreamed. Since the packages involved have changed over the months (shark-turbine --> iree-turbine naming, see also https://github.com/iree-org/iree-turbine/issues/28), I also updated the document to reflect the current setup.
The `iree-requirements.txt` file was being used to pin versions of the `iree-compiler` and `iree-runtime` that would be released together with this `iree-turbine` package. That was overlooked when https://github.com/iree-org/iree-turbine/pull/115 removed pins from that …
> Bump version to 2.5.0 and document release process.

- README.md
- build_tools/post_pypi_release_test.sh
- docs/releasing.md
- iree-requirements-ci.txt
- iree-requirements.txt
- iree/turbine/aot/builtins/globals.py
- iree/turbine/aot/support/procedural/exported_program.py
- iree/turbine/dynamo/tensor.py
- setup.py
IREE is renaming its Python packages from `iree-compiler` and `iree-runtime` to `iree-base-compiler` and `iree-base-runtime`, in order to switch to a new versioning scheme: https://github.com/iree-org/iree/issues/18938. This switches to using the new package names and versions and cleans up some related documentation along the way.
Note: the new packages are not yet built and published, hence this is a draft PR. Once packages are published we can rebase, test this, and then proceed.
> Switch to new IREE package names and versions.

- version_info.json
I think this will let source builds appear as newer than the stable PyPI release that was just published (https://pypi.org/project/iree-turbine/2.9.0/). We can iterate on the release process sequencing next week. Maybe we shouldn't touch this version, or maybe we should update the minor version instead of the patch version, I'm not sure.
> Update package version to 2.9.1.

- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_attention_test.py
- tests/kernel/wave/wave_e2e_test.py
- tests/kernel/wave/wave_gemm_test.py
Move default run config to common function
> [TKW] Refactor test run config

- tests/kernel/wave/wave_attention_test.py
This PR provides a short term fix for the failing tests. When the Q matrix is not promoted, scheduling fails. So for now, we promote the Q matrix.
> Promote Q matrix

- .github/workflows/ci-tk.yaml
- .github/workflows/perf.yaml
- build_tools/build_release.py
- docs/releasing.md
- iree-requirements-ci.txt
- iree/turbine/kernel/compiler/dispatch_codegen.py
- version_info.json
See the release tracker at https://github.com/iree-org/iree/issues/19063.
> Bump to depend on iree 3.0.0 packages.

- iree/turbine/kernel/wave/__init__.py
- iree/turbine/kernel/wave/assumptions.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/scheduling/schedule.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/assumptions_test.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds tests for dynamic M and N dims in
GEMMs. This works out of the box for the most part
and just requires moving the align index pass
after scheduling.
> Add support for dynamic parallel dims in GEMMs

- iree-requirements-ci.txt
- iree/turbine/kernel/compiler/dispatch_codegen.py
- iree/turbine/kernel/compiler/ir.py
This PR updates the dispatch codegen to use the
new attributes for translation info. Also updates
the ci requirements to last night's pre-release
to get the latest changes.
> Update translation info related attributes

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/minimize_global_loads.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_gemm_test.py
In order to enable Fp8 attention, we first need introduce the same 16x16x32xf8 intrinsic with k-Width=4. This is required S.T we can use it for the second gemm/contraction in attention so that the layouts between the gemms will match and we won't have to do a round trip to shared memory. 
Since the native size of 16x16x32xf8 is kWidth=8, this new virtual intrinsic with k-Width=4, will need to do two interleaved reads of 4xf8 instead of a single 8xf8 read. This interleaved reads will looks something like:
```
[0, 0, 0, 0, 16, 16, 16, 16, 32, 32, 32, 32, 48, 48, 48, 48, 0, 0, 0, 0, 16, 16, 16, 16, 32, 32, 32, 32, 48, 48, 48, 48]
Where the entry represent the lane it is owned by. 
```
We can see that in this case, since lane0 needs data from index [0:4) and index[16:20), we'd need to do two …
> [TKW] Implement MFMA F8 intrinsic/layout with interleaved reads based on VGPR

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/wave_attention_test.py
In order to align layouts in chained gemm or attention inFP8, we'd need to use different intrinsics for the 1st and 2nd mma. In order to achieve this, we'd need to do:
1. Set optional MMA_Type as an arg in tkw.mma
2. Modify index_seq_analysis and constraints to use the MMAOp's intrinsic type as opposed to the hw_constraint type when available.
> [TKW] Enable each MMA to have it's own intrinsic

- iree-requirements-ci.txt
- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/codegen.py
Previously, ceildiv did not lower through the IREE backend and so we had to manually add the decomposition of ceildiv in codegen. Now, that the upstream PR has landed, we can go back to using ceildiv in codegen.
> Modify codegen lowering to use ceildiv

- iree/turbine/kernel/wave/wave.py
This updates the instructions for patching LLVM with the fixes to preserve our scheduling decisions.
The old instructions do not fetch the commit anymore. The cherry-pick yielded the error: `fatal: bad object ee52732cddae42deed2e3387a83b20ec05860b4e`.
I changed this to only fetch the relevant commit.
> Update LLVM patch instructions

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/thread_shape_analysis.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention.py
- lit_tests/kernel/wave/expansion.py
- tests/kernel/wave/wave_attention_test.py
This PR adds a major refactor of the index sequence analysis. Specifically,
1. Index sequence computation is broken down into two phases - a thread independent index which is calculated with one pass through the graph.
2. And a thread dependent index which is computed by propagating indices from nodes such as MMA, Read or Write.
3. A heuristic is added to determine how to propagate information in case of multiple nodes competing for a given node based on dimensional analysis
4. An additional unit test is added for attention expansion
5. An e2e test for attention with bias is added
> Add propagation of thread dependent index sequences

- .github/workflows/ci-tk.yaml
- iree/turbine/kernel/wave/hoisting.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/scheduling_test.py
- tests/kernel/wave/wave_attention_test.py
In flash attention, Q's reduction dimension is typically relatively small, and hence we do only have reduction tile across K2 dimension/reduction dimension of 2nd gemm(P and V). Hence, an optimization we can do is to hoist reading of Q from global memory out of the for loop, this actually generates quite a big speedup (hoistQ + use global->register for Q gives typically 2x speed up.)
To implement the optimization above, we needed to add:
1. Expand `hoisting.py` to also look for `Read` that is:
- independent of induction variable
- has memory that is read-only/do not have write as users (i.e important for correctness since this guarantee data being read is constant/not changing with loop)
- has memory who is a captured_var (i.e memory can be traced to outside the loop) 
2. Implement method …
> [TKW] Hoist loop invariant reads

- iree/turbine/kernel/kernels.py
- iree/turbine/kernel/wave/templates/__init__.py
- iree/turbine/kernel/wave/templates/conv.py
- tests/kernel/wave/wave_e2e_test.py
Move TKW IGEMM conv impl from the test folder to some common place to allow it to be reused outside the tests (e.g. in iree-kernel-benchmark).
Not sure what the proper place for it, suggestions are welcome.
> [TKW] Move IGEMM conv impl to common place.

- iree-requirements-ci.txt
- iree/turbine/aot/build_actions.py
- iree/turbine/aot/testing/example_builder.py
- mypy.ini
- tests/aot/turbine_generate_test.py
This supports performing parallelizable aot model export as part of the iree.build tool. By default, it runs actions out of process, meaning that multiple torch.export and torch-mlir imports can be running with true concurrency.
> [iree.build] Add `turbine_generate` iree.build rule.

- iree/turbine/kernel/wave/utils.py
- tests/kernel/wave/wave_attention_test.py
- tests/kernel/wave/wave_e2e_test.py
- tests/kernel/wave/wave_gemm_test.py
Moved default scheduling params to `get_default_scheduling_params()`.
> [TKW] Move default scheduling params to common place

- iree/turbine/kernel/wave/templates/conv.py
- tests/kernel/wave/wave_e2e_test.py
Add `input_dtype`/`output_dtype` to igemm_conv template API, only f16xf16xf32 is supported for now but it will be extended in future.
> [TKW] Add dtype to igemm conv template

- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
Add a `create_vmfb_file` flag to run full IREE pipeline to get vmfb file without actually invoking anything.
This is a quick hack to get iree-kernel-benchmark going until we have a proper AOT compilation API.
> [TKW] Add `create_vmfb_file` option

- iree/turbine/kernel/_support/dtype.py
- iree/turbine/kernel/lang/__init__.py
- iree/turbine/kernel/lang/global_symbols.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/templates/evoformer.py
- iree/turbine/kernel/wave/thread_shape_analysis.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention.py
- requirements.txt
- tests/kernel/wave/constraints_test.py
- tests/kernel/wave/wave_evoformer_test.py
This PR adds an e2e test for the evoformer for
specific shapes and dtypes. It also adds support
for bf16 types.
> Add evoformer example

- iree/turbine/kernel/wave/utils.py
- tests/kernel/wave/wave_evoformer_test.py
The waves_per_eu flag is a optimization hint
that specifies the minimum number of waves per
execution unit.
> Add support for waves_per_eu flag

- iree/turbine/kernel/wave/thread_shape_analysis.py
This PR fixes the type annotation of
a function in thread_shape_analysis to
capture the output type.
> Fix type annotation on function

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_utils_test.py
Add utility to detect contiguous access pattern in mapped reads/writes so we can use contiguous vector ops instead of gathers/scatters during lowering.
Iterate over `elements_per_thread` and check if every subsequent mapped index have only diff of 1 in fastest changing dim.
Also, it need some custom sympy simplifications to successfully work on IGEMM conv.
> [TKW] Detect contiguous access pattern in mapped reads/writes

- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/attention.py
- lit_tests/kernel/wave/mma.py
There are issues with current index_seq_analysis that made our software chunked supposedly vectorizable writes into chunks of vector.store vector<1xf32>.
In order to fix this we needed:
1. Adjusted IndexSeq generated from partition_gpr_offset to modify only the dim with gpr_offset to size of gpr_size and have stride of 1(iff gpr_offset_dim is or will be fastest dim). It used to set every dimensions in simplified index to gpr_size which is incorrect.
2. Refactored codegen of _construct_gather_scatter_indices S.T our writes with mapping can handle case where fastest dimension is not necessarily the last dimension (i.e no layout change - transposed case).
On attention dispatch146(B0: 2, B1: 20, (M, K2): 1024: K1: 64) it improved performance from 6.0 ms to 5.5 ms.
> [TKW] Fix to do vectorized reads/writes when possible.

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/templates/evoformer.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_attention_test.py
Doing divf is very expensive on the GPU. We introduce reciprocalOp S.T we can use it to do a single divf on online attention's sum, which we can then apply to the attention output for normalization using mul.
This will allow us to only do a divf on a single f32 as opposed to the entire vector. Which will give us speed up of around 0.1 ms per dispatch on dispatch146(B0: 2, B1: 20, (M, K2): 1024: K1: 64) (after vectorized write land it drops from 5.53ms -> 5.38 ms)
> [TKW] Introduce ReciprocalOp for faster attention

- iree/turbine/kernel/compiler/dispatch_codegen.py
- iree/turbine/kernel/compiler/ir.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/wave_attention_test.py
- tests/kernel/wave/wave_evoformer_test.py
For flash attention, denormal-fp-math-f32" = "preserve-sign" is very important optimization. With this flag, we are able to drop latency from 5.38ms to 4.75ms on dispatch146(B0: 2, B1: 20, (M, K2): 1024: K1: 64).
Added compile_config S.T we can use it as a parameter for kernel cacher as well.
> [TKW] Implement pipeline to enable llvm_func_attrs and denormal_math

- .github/workflows/ci.yaml
- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/lang/wave_types.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/scheduling/schedule.py
- iree/turbine/support/debugging.py
- iree/turbine/tools/interpreter.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/scheduling.py
- requirements.txt
- setup.py
Also updated enough of the project to pass these new test configurations:
* Avoid starred expressions in indexes for Python < 3.11 (https://stackoverflow.com/a/77080166, https://stackoverflow.com/q/77580216)
* Import `Self` from `typing_extensions` for Python < 3.11 (https://stackoverflow.com/a/77247460)
* Limit use of `logger.getLevelNamesMapping` to Python >= 3.11 (https://docs.python.org/3/library/logging.html#logging.getLevelNamesMapping, see also https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks)
* Stop using `unittest` in files that don't need it, fixing exit code 5 in Python >= 3.12 for "no tests were run" (https://docs.python.org/3/library/unittest.html#unittest.main)
> Run unit tests across Python versions 3.10-3.12.

- iree-requirements-ci.txt
- iree/turbine/kernel/compiler/ir.py
ROCDL dialect is required to do use setprio for performant scheduling
> [TKW] Update iree-requirements and integrate rocdl_d

- iree/turbine/kernel/wave/scheduling/graph_utils.py
- iree/turbine/kernel/wave/scheduling/modulo_scheduling.py
Processes created by `multiprocessing.Pool` have `daemon` flag which forbids to create child processes (e.g. from nested `multiprocessing.Pool`). Fallback to single-process compilation in this case. This fixes a crash when compilation itself is called from inside `multiprocessing.Pool` processes.
> [TKW] Avoid nested `multiprocessing.Pool` usage

- iree/turbine/kernel/wave/decompose_reduce_ops.py
- lit_tests/kernel/wave/attention.py
Max reduction can make use of v_max3_f32 which is much faster than regular v_max_f32. However to enable this we'd need to scalarize the local reduction more S.T LLVM compiler can do this optimization better. (drop latency from
4.5 ms to ~4.3 ms on dispatch146(B0: 2, B1: 20, (M, K2): 1024: K1: 64)
> [TKW] Scalarized local reduction for faster Max

- README.md
- iree/turbine/__init__.py
- setup.py
Instead of enforcing the installation for 'torch' as a dependency, error if 'torch' cannot be imported and point the user to how to install.
> Remove 'torch' from deps and warn instead

- pytorch-cpu-requirements.txt
- pytorch-rocm-requirements.txt
We have some test failures with 2.6.0 prereleases: https://github.com/iree-org/iree-turbine/actions/runs/12399117695?pr=346. Sticking to stable versions until we can triage.
> Switch torch requirements back to stable channel.

- .github/workflows/ci-tk.yaml
- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/wave.py
- tests/kernel/wave/runtime/cache_test.py
* Disable filesystem-based kernel caching by default as it too human error prone
* Do not access `cache_manager` and do not compute kernel hash if caching is disabled.
* Only run cache tests is caching is enabled
> [TKW] Kernel cache changes

- iree/turbine/kernel/_support/indexing.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
* Properly propagate index through chained read.write ops using `transform_index_backwards`
* Use proper symbols for dynamic vals
* Do not propagate 0 index
> [TKW] Fix chained dynamic vals

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/expansion.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/symbolic_constraints.py
- iree/turbine/kernel/wave/templates/decode_attention.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/wave_attention_test.py
This PR at support for a new variant of flash decoding. In this version we use a split – K approach, where the first kernel compute the attention parallelizing over the sequence length, and the second kernel sums up all the results. In order to make this work, we had to add support for the following
- SymbolicAliases - these are language constructs that allow us to say that one symbol is associated with another symbol with a specific relationship. This is implemented as constructing additional work group constraints telling constraints and wave constraints. They are ignored during expansion.
- Added a template for flash decoding that is used in both the lit test as well as the end to end tests
> Add flash decode v2

- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/codegen.py
Integer range inference is broken for `arith.ceildivsi` (see https://github.com/iree-org/iree-turbine/pull/354#issuecomment-2560436649), switch to ceildiv emulation again.
> [TKW] Emulate ceildiv again

- iree-requirements-ci.txt
We're approaching our 3.1.0 release across all IREE packages (https://github.com/iree-org/iree/issues/19192), so testing closer to HEAD.
Commit range: https://github.com/iree-org/iree/compare/iree-3.1.0rc20241212...iree-3.1.0rc20241220
> Bump tested IREE version to most recent nightly.

- iree-requirements-ci.txt
We have a release candidate for https://github.com/iree-org/iree/issues/19192. Switching to test it.
Commit range: https://github.com/iree-org/iree/compare/iree-3.1.0rc20250103...iree-3.1.0rc20250107
> Bump tested IREE versions to the latest release candidate.

- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/templates/decode_attention.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/decode_attention_test.py
After the new expansion PR, the new intrinsics and larger
tile sizes are supported.
This PR additionally adds support for lowering sympy.pow,
and binary add operators with more than 3 arguments
which is required for lowering dynamic shapes.
> [FlashDec] Add support for more intrinsics & larger tile sizes

- .github/workflows/ci-tk.yaml
- .github/workflows/ci.yaml
- .github/workflows/perf.yaml
- MANIFEST.in
- build_tools/build_release.py
- iree-requirements.txt
- mypy-requirements.txt
- requirements-iree-pinned.txt
- requirements-iree-unpinned.txt
- requirements.txt
This is preparation for adding automation to handle updating dependency versions.
* Renamed `iree-requirements.txt` and `iree-requirements-ci.txt` to `requirements-iree-[un]pinned.txt` so they sort next to other `requirements-*.txt` files and match the names used downstream in https://github.com/nod-ai/shark-ai.
* Deleted `MANIFEST.in` that was unused since `package_data` in `setup.py` does what those `include` lines used to: https://github.com/iree-org/iree-turbine/blob/e4550f37dcd8b9b691db93c30b478c1d67eee83b/setup.py#L97-L100
* Sorted dependencies in `requirements.txt`.
* Deleted unused `mypy-requirements.txt`.
> Cleanup requirements and packaging files.

- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/decompose_vmma_ops.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/gemm.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/wave_gemm_test.py
To improve performance on attention, we add virtual MMA layout to maximize read/loads from shared memory to register. We also add decomposition for these virtual MMA layout that converts virtual MMA + coalesced reads -> unrolled MMA + unrolled broken apart reads.  The decomposition for VMMA is done in three steps:
1. Collect all MMA ops and only process the ones with virtual intrinsics.
2. For each VirtualMMAOp, we generate check it's unroll factor
3. Generate slices of lhs and rhs from coaleseced reads based on native and virtual MMA sizes
4. Generate native MMA ops based on unroll factor that takes in slices of coaleseced lhs and rhs
5. Modify index expression of new mma op by replacing the expression based on virtual layout
with it's equivalent native layout expression.
> [TKW] Add layout to maximize shared reads

- iree/turbine/kernel/_support/tracing.py
- iree/turbine/kernel/compiler/host_codegen.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/expansion/expansion_utils.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
* `set_symbol` op to set specific symbol to some dynamic value (i.e. read from memory) during codegen, this is mostly a hack until we have a proper support for slices/reductions with dynamic sizes/tilesizes.
* `apply_expr` op to allow nontrivial index calculations.
> [TKW] `set_symbol` and `apply_expr` ops

- .github/workflows/update_iree_requirement_pins.yml
This allows the created pull requests to run checks based on the `pull_request` trigger. See the documentation here:
* https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
* https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
Sample PR: https://github.com/iree-org/iree-turbine/pull/390
> Generate token for create-pull-request action using an app.

- iree/turbine/kernel/_support/regions.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/expansion/expansion_utils.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/symbolic_constraints.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- iree/turbine/kernel/wave/type_inference.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/paged_attention_test.py
This PR adds a functional paged decode attention kernel. To get this working, the following changes were made:
1. Add support for sympy.Min, sympy.Piecewise
2. Add paged decode attention kernel with test with vLLM and Sglang reference
3. Bookkeeping of lifted variables to track implicit captures
4. Updates to expansion to handle MMA reductions where the none of the MMA reduction dims match the reduction dim of the parent op
5. Updates to expansion to expand symbols that have no constraints on them
6. Better handling of SetSymbol and ApplyExpr in expansion and other passes
7. Adds the notion of a primary and non-primary workgroup constraint. Primary workgroup constraints are used to determine the grid shape. Non-primary constraints can use the same workgroup id but are not used to …
> Paged Decode Attention

- .github/workflows/build_packages.yml
This will allow downstream workflows like https://github.com/nod-ai/shark-ai/blob/main/.github/workflows/update_iree_requirement_pins.yml to get nightly IREE and iree-turbine packages without waiting longer.
See that https://github.com/nod-ai/shark-ai/pull/835 got these versions due to the timing:
```
iree-base-compiler==3.2.0rc20250120
iree-base-runtime==3.2.0rc20250120
iree-turbine==3.2.0rc20250119
```
> Reschedule nightly build_packages.yml workflow.

- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/lang/kernel_buffer.py
- iree/turbine/kernel/lang/wave_types.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/paged_attention_test.py
This PR introduces a memory layout attribute for the MemoryType that allows the user to specify a physical shape that differs from the logical shape. This is useful in scenarios like kv-caches where certain dimensions physically are quite large but map to fixed logical dimensions.
> Allow specification of logical and physical layouts

- .gitignore
- iree/turbine/kernel/wave/expansion/expansion.py
- lit_tests/kernel/wave/expansion.py
Right now, it only looks at write nodes in the root graph and misses ones in reductions. Instead we walk all the regions for `Write` nodes and `GetResult` nodes without users.
`get_leaf_node_types` also appeared to always return `[Write]` as it sets `leaf_nodes` to that and then immediately checks if it's empty, which it never will be, so I deleted it.
Also includes some .gitignore additions that I can drop if you don't like them.
Fixes https://github.com/iree-org/iree-turbine/issues/374
> Expand from write nodes inside reductions

- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/wave_sim_test.py
`assert_close` is the replacement. See
https://pytorch.org/docs/stable/testing.html#torch.testing.assert_allclose
Deprecation warnings annoy me 😛
> Replace deprecated `assert_allclose`

- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/paged_attention_test.py
This PR removes the permutation of the key and
value cache prior to kernel invocation.
> Remove permutation of KV cache

- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/wave_sim_test.py
Includes fixes for the cache tests, which I missed because I have been leaving the cache turned off.
This reverts commit 1847c33.
> Reland "Replace deprecated `assert_allclose` (#405)"

- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/paged_attention_test.py
This PR updates the grid distribution for paged decode attention. Previously, we were launching only as many workgroups as there were kv heads. However, if instead we can exploit much more parallelism if instead we launch ```shape.num_query_heads // min(HEAD_BLOCK_SIZE, head_ratio)``` workgroups and do some arithmetic on the workgroup index to recover the kv head index.
> Update grid size for PDA

- iree/turbine/kernel/_support/tracing.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/paged_attention_test.py
* Fix `proxy.create_arg` as `sympy.StrictlyLessThan` and friends are not subclass of sympy.Expr.
* It is now possible to directly use sympy expressions in `@conditional` arg.
* Fix `DCE` to not remove ops if they contain nested ops with side-effects (e.g. writes inside conditional).
* Update `get_users`/`get_inputs`/`node_args` ops to properly handle vars captured through placeholders.
* Update `CustomOp.erase` to cleanup dead captures when deleting placeholders.
* Update paged attention template.
> [TKW] Fixes for `@conditional` and paged attention

- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/tracing.py
I found these very helpful while debugging. I actually didn't realize there was a `print_trace` function before, so I had modified the `__str__` method on `CapturedTrace`. I've adapted it to use `print_trace` instead. I ported over some of the things I put in the `__str__` method though, like labels for the regions. I think those might be useful for lit tests as well (I had to update the lit tests for it).
Note that I removed a number of comments that mostly repeated the name of the function. I kept ones that seemed like they were elaborating though.
> Add print options to Wave pass pipeline

- requirements.txt
Missed in https://github.com/iree-org/iree-turbine/pull/431.
> Pin torch to <2.6.0 in requirements.txt.

- .github/workflows/ci-tk.yaml
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/templates/prefill_attention.py
- iree/turbine/kernel/wave/templates/vanilla_attention.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/prefill_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
This PR adds an implementation of prefill attention. In prefill attention, we have variable length sequences and so we need to pass in the start offsets as well as the lengths of the sequences. The setting of the offsets and variable sequence lengths is accomplished using set_symbol.
Also, this PR adds the ability to specify the total count for a work group constraint and adds attention cleanups.
> Prefill Attention

- README.md
- docs/README.md
- setup.py
Progress on https://github.com/iree-org/iree-turbine/issues/77.
Note that the README is included at https://pypi.org/project/iree-turbine/ too.
* Status badge showing readthedocs build status
* Link to https://iree-turbine.readthedocs.io/
* Switch pytorch install instructions off of the `test` channel
* Document readthedocs dashboard and publishing mechanism
> Add links to the new documentation website.

- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/templates/prefill_attention.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/prefill_attention_test.py
This PR implements missing feature to enabled GQA for non-transposedV on prefill attention. In order to do that there are two main things this PR introduces:
1. GQA by definition dictates that Q_head >> KV_head. However, previously we set the same symbolic dims `H` on `Q_head` and `KV_head`, this ends up giving incorrect result during GQA non transposedV extend attention. For example, in the case of `seq_len=64, q_head=4, kv_head=1, h_dim=128` with same symbolic dim, it still expect v_shape of (tensor<64x4x128xf16>) which will produce transposed-v read/gather with `stride=128*4=512` but in reality it should be `tensor<64x1x128xf16>` with `stride=128*1=128`.
2. Once we have the proper/correct "non-primary" workgroup constraint set, kernel starts giving numerically wrong results. Upon …
> [Wave] Improve support for non-primary wg constraint to fix GQA decode

- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/extend_attention_test.py
This PR removes the need for the value tensors to be permuted for the attention kernel.
> Remove transpose v in extend attention

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/codegen.py
The tkw.minimum(elementwise) is lowered into arith::MinimumFOp, arith::MinisIOp, and arith::MiniuIOp for floats, signed and unsigned integers respectively
Fixes: #339
> [TKW] Add MinimumOp as an op for Quantized LLM and GenAI workload

- .github/workflows/build_packages.yml
- build_tools/compute_local_version.py
We can't make multiple different versions for the same day.
With this change the release candidates will have a version of the form
3.2.0rc20250205.0
3.2.0rc20250205.1
...
instead of just
3.2.0rc20250205
> Include numbered version for release candidates

- iree/turbine/kernel/_support/indexing.py
- iree/turbine/kernel/compiler/dispatch_codegen.py
- iree/turbine/kernel/compiler/host_codegen.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
This PR modifies the extend attention kernel so that the query/key/value/output extend sequence length is dynamic. This is required to avoid recompilation of the kernel for different values of the sequence length.
> [Wave] Make extend sequence dimension dynamic

- docs/core/support.rst
- iree/turbine/support/conversions.py
- iree/turbine/support/tools.py
- tests/support/conversions_test.py
- tests/support/tools_test.py
One drawback of using npy files is that they don't support some datatypes.
This change adds functionality to prepare arguments from Torch tensors in the form
--input=1x2xbf16=@arg0.bin
These can then be passed to tools like iree-run-module and iree-benchmark-module.
> Add functions that prepare tensors as input args for IREE tools

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/scheduling/graph_utils.py
- iree/turbine/kernel/wave/scheduling/resources.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/templates/vanilla_attention.py
- lit_tests/kernel/wave/attention/attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/common/shapes.py
Most time on LLM, we'd be facing unaligned shapes since sequence length is not always aligned/padded. In order to support that, we implement unaligned attention kernel along with a couple compiler features S.T we can handle unaligned shapes. Features are:
1. Implement `&` operator to combine multiple masks (causal + unaligned shape)
2. Teach broadcast to handle symbolic broadcasts on unit dims as no-op (important for broadcasting K2 -> [M, K2] for masks)
3. Let ApplyExpr go through expansion, initially caused a numeric bug if not expanded properly.
4. Modify necessary LIT to check for unaligned mask, and e2e to handle unaligned shape
> [Wave] Teach compiler to handle unaligned attention

- iree/turbine/kernel/wave/cache.py
Different input arguments can have the same logical shape but different physical shape, so we add the physical layout to the key when caching the kernel.
> [Wave] Add physical layout to cache key

- .github/workflows/build_packages.yml
Reverts iree-org/iree-turbine#458.
The workflow failed: https://github.com/iree-org/iree-turbine/actions/runs/13172140306/job/36764292832. See also https://github.com/iree-org/iree-turbine/pull/458#discussion_r1945051587.
> Revert "Include numbered version for release candidates"

- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/templates/alibi_attention.py
- tests/kernel/wave/attention/alibi_attention_test.py
This implements (causal) ALiBi, attention with linear biases, following
the paper "Train Short, Test Long: Attention with Linear Biases Enables
Input Length Extrapolation" by Press et.al in ICLR 2022.
> Attention with Linear Biases

- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/utils.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/common/shapes.py
This PR fixes the benchmarking code to work for extend attention. Extend attention can now be profiled using:
pytest -s tests/kernel/wave/attention/extend_attention_test.py --runperf --run-e2e --dump-perf-files-path=<path>
> [Wave] Get runperf working for extend attention

- iree/turbine/kernel/wave/cache.py
- tests/kernel/wave/runtime/cache_test.py
Previously free variables such as mfma variants, logit_caps, or is_causal flags are not used as keys for caching. This may cause numerics issues in real life use case.
> [Wave] Add free variable as key to WaveCacher

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
This PR adds the following fixes to extend attention:
1. Fixes the way the block indices were being read for the v matrix in the first loop. Because of the layout differences between the first and second mma, we need to read block indices with a different layout and correspondingly elements per thread when loading from the kv cache.
2. Moves the qk-transpose scaling inside the kernel for accuracy reasons.
3. Moves reuse shared allocs pass after minimize global loads.
4. Minor compiler fix regarding use of Sequence vs list
> [Wave] Fixes to extend attention 

- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
In order to prevent re-compile when number of sequence changes, we modify kernel to handle dynamic num_seqs
> [Wave] Make num_seq to dynamic for Extend Attention

- iree/turbine/kernel/wave/reuse_shared_allocs.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention/extend_attention.py
* Move `reuse_shared_allocs` after `minimize_global_loads`, as `minimize_global_loads` gets confused by the new alloc structure.
* Insert barrier when replacing alloc to make sure all threads finished their reads/writes to would-be-reused alloc.
* Do not kill `SharedMemoryBarrier` by `DCE`
> [TKW] Reuse allocs fix

- iree/turbine/kernel/compiler/host_codegen.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
This PR makes the maximum extend sequence a dynamic kernel argument that is used in the grid calculation. 
Tested with gsm8k to 0.816.
> [Wave] Make maximum extend sequence length dynamic

- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/templates/alibi_attention.py
- tests/kernel/wave/attention/alibi_attention_test.py
This implements (causal) ALiBi, attention with linear biases, following
the paper "Train Short, Test Long: Attention with Linear Biases Enables
Input Length Extrapolation" by Press et.al in ICLR 2022.
Incidentally fixes API misuse in code generation for broadcast.
Reland #467
> Reland Attention with Linear Biases

- iree/turbine/kernel/wave/decompose_vmma_ops.py
- lit_tests/kernel/wave/gemm.py
This handles support of VMFMA for broadcasted batched gemm. i.e the batch size of one of the operand is broadcasted onto the other. i.e this is to support virtual MMA intrinsics in GQA. 
For example in a GQA like gemm we will have (B_KV, M, K) * (B, K, N) -> (B, M, N). In this case, with set operation alone it is hard to see that `B_KV` is also a batch dimension and not M-dim.  
Initial prototype adds an additional set intersection with acc_index.type. Whilst that would work for some cases, it wouldn't work for the operand with the same batch size as the acc/output. i.e in our case above we will fail to determine the right N-dim.
m-dim = (B_KV, M, K)  - (B, K, N)  ∩  (B, M, N) = (M,) - OK
n-dim =  (B, K, N)  - (B_KV, M, K)  ∩  (B, M, N) = (B, N) - NG
Hence, we added a filter that ensures …
> [Wave] Teach compiler to handle batched MMA for VMFMAOps

- docs/core/support.rst
- iree/turbine/support/tools.py
This fixes the wrong docstring introduced by #418.
> Fix doc for functions that prepare IREE tools' input args

- iree/turbine/kernel/wave/codegen/read_write.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/attention/extend_attention_test.py
* Split read/write ops indexing on thread-dependent and thread-independent.
* Use symbolic vals for strides instead of extracting them from memref.
* For now only replace gather/scatter ops with buffer ops.
> [TKW] Work on buffer ops

- examples/aot_mlp/README.md
- examples/aot_mlp/mlp_export_simple.py
- examples/aot_mlp/requirements.txt
This pull request includes the following main changes:
1. Added assertions to the `aot_mlp` example.
2. Replaced print statements with loggers.
3. Added r`equirements.txt` for the `aot_mlp` example.
4. Added a `README.md` file for the `aot_mlp` example.
> Added readme to the aot_mlp example

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/codegen/read_write.py
- iree/turbine/kernel/wave/global_to_shared_gathers.py
- iree/turbine/kernel/wave/minimize_global_loads.py
- iree/turbine/kernel/wave/promotion.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/evoformer.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/attention/prefill_attention.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
This PR adds support for transforming gathers from global memory to gather to shared memory. In order to do this,
we modify the loads from global and stores to shared to use all the threads available and then use gathers to obtain
the data from shared memory.
We add a new pass that closely follows minimize global loads as well as other changes to enable this.
> Global to shared gathers

- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/templates/t5_rpe_attention.py
* `gen_sympy_index`: allow broadcasting between `vector<1xT>` and `vector<NxT>`
* Allows to get rid of explicit broadcast in rpe kernel.
> [TKW] Improve `gen_sympy_index` broadcasting

- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/templates/t5_rpe_attention.py
- tests/kernel/wave/attention/t5_rpe_attention_test.py
* Add missing `subs_idxc` in `has_gpr_offsets`
* Handle `mapping_dynamic_vals` for read/write ops in `has_gpr_offsets`
* Propagate index to generated `Reshape` op, which needed for proper detection dynamic vals handling
* Use `STORE_ELEMS_PER_THREAD` for RPE read in RPE kernel as the result is combined with mma result
* Remove `elements_per_thread` from `self_index` as they can be inferred
> [TKW] Fix RPE 32x32x8 MMA

- iree/turbine/kernel/wave/utils.py
Polynomial approximation causes major slowdown, so we add a IREE compile flag to remove it. The changes wouldn't be visible at Wave level but will give good perf boost in generated LLVMIR
> [Wave] Remove polynomial approx with iree compile flag

- iree/turbine/kernel/wave/utils.py
- tests/kernel/wave/attention/extend_attention_test.py
We are converting kernel args to dlpack capsule to feed them into IREE runtime, unfortunately, IREE runtime renames all incoming capsules from "dltensor" to "dltensor_used" for some reason and also will never delete capsule if its name not a "dltensor". This causes incoming tensors lifetime to be prolonged indefinitely and to be never released.
Rename capsule back after `device.from_dlpack_capsule`
> [TKW] Fix memory leak

- iree/turbine/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/attention/pipelined_attention.py
- lit_tests/kernel/wave/attention/prefill_attention.py
Previously, `partition_strided_operators` was always partitioning writes if input register index was strided. Add an additional check if the result partitioned writes are equivalent to contiguous when combined with index and mapping.
This helps to vectorize various attention kernels result writes.
> [TKW] Less conservative partition

- iree/turbine/kernel/wave/codegen/read_write.py
Add a special case when masked load/store mask is result of `vector.splat`. In this case we don't need to unroll the op and instead can use vector buffer ops directly.
> [TKW] Use buffer ops for splatted masked load/stores

- iree/turbine/kernel/wave/assumptions.py
- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/symbolic_constraints.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- tests/kernel/wave/runtime/cache_test.py
This PR annotates the get_hash function for retrieving cached kernels with functools.lru_cache to ensure that we don't pay the cost for computing the hash for a particular kernel more than once per session.
get_hash used to take 2.5ms, and with this PR that goes down to 0.9ms , since we are avoiding the hash calculation and just doing a lookup.
> Use LRU cache when retrieving kernel hash

- iree/turbine/kernel/wave/templates/extend_attention_rpe.py
- tests/kernel/wave/attention/extend_attention_test.py
Need to use `STORE_ELEMS_PER_THREAD` for RPE as we are applying RPE to mma accumulator.
> [TKW] Extend attention RPE `F32_32x32x8_F16`

- iree/turbine/kernel/wave/assumptions.py
- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/symbolic_constraints.py
- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/runtime/cache_test.py
This PR improves the way caching was done. Rather than use functools.lru_cache, users can now pass in a kernel_hash argument which will return the kernel hash for the kernel. This can then be reused in subsequent calls to avoid the hash computation.
Furthermore, we add a runtime cache to cache the system context and function to lower overheads.
> Improvements to caching

- iree/turbine/kernel/wave/wave.py
Emit a warning if IREE version is too low. Warning is only emitted when we trying to compile kernel, so if users don't use Wave they won't see it. We also don't emit it if user uses a cached kernel to not add any additional overhead to 'happy' path.
> [TKW] Warn if IREE versions is too low

- tests/kernel/wave/attention/extend_attention_test.py
This creates annoying warning spam. See
https://github.com/iree-org/iree-turbine/pull/421.
> Replace deprecated assert_allclose

- iree/turbine/kernel/wave/profiling.py
- iree/turbine/kernel/wave/utils.py
This PR adds the ability to capture profiling traces during benchmarking by adding the capture_trace
key to the config and specifying its value as the path where the traces should be stored.
> [Wave] Add ability to capture traces while benchmarking

- tests/kernel/wave/attention/extend_attention_test.py
We are distributing tests over multiple GPUs in CI, so all tensors must be allocated using our `device_xyz` wrappers.
> [TKW] Fix device in extend attention test

- tests/dynamo/tensor_test.py
See https://github.com/iree-org/iree-turbine/issues/317.
Not sure why this test is failing on CI and can't reproduce locally. The other tests in the file appear to be working as expected.
Given that our JIT / dynamo / torch.compile path is currently a lower priority than the aot / torch.export path, I'm okay with disabling this test for now.
> Skip failing `tests/dynamo/tensor_test.py::TensorTest::test_nn_ML`.

- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/utils.py
This PR reduces the time taken to execute a kernel on the CPU. It accomplishes this by caching the UUID of devices, caching the loading of kernel files and switching to the to_dlpack API to avoid an additional call to __dlpack__.
> [Wave] Cache computation of uuid and loading of cached kernel

- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention/attention.py
- lit_tests/kernel/wave/attention/attention_bias.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/evoformer.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/attention/pipelined_attention.py
- lit_tests/kernel/wave/attention/prefill_attention.py
- lit_tests/kernel/wave/casting.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/gemm.py
- lit_tests/kernel/wave/igemm.py
- lit_tests/kernel/wave/mma.py
- tests/kernel/wave/attention/chained_gemm_test.py
- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/evoformer_test.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/wave_gemm_test.py
- tests/tools/interpreter_test.py
Cached kernels were returning the asm and uncached ones were returning the module builder.
I added cache statistics to the `WaveCacheManager` instead of the cache test using the returned type to distinguish a cache hit. I also renamed the `module_op` property on `WaveCache` to `asm as that's actually what it is (treating it like it was a module op was what was causing failures in the first place).
Another option would be to consistently return a dataclass that has the extra information present in `WaveCache`, but I didn't want to use a cache type the path where the cache is turned off and `WaveCache` also fetches asm lazily, which complicates things a bit. I think we'd want a `WaveKernel` type and two duck-typed implementations if we went that route.
Fixes …
> [TKW] Consistently return asm in test execution

- lit_tests/kernel/wave/attention/attention.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/common/utils.py
2 minor changes:
1) Changes to lit checks required to run with my version of lit. I suspect older versions get confused by
#CHECK-DAG immediately followed by #CHECK, and by CHECK-LABELS with variables to match. 
2) additional information when torch isn't installed with support for CDNA (FWIW: must install pytorch-rocm-requirements.txt)
> [Wave] Tweak lit tests to support older lit 

- iree/turbine/kernel/wave/README.md
Nested lists need a bit more indentation, headings should be surrounded by empty lines.
> [Wave] Minor formatting tweaks to wave/README.md.

- iree/turbine/kernel/wave/scheduling/loop_reconstruction.py
- iree/turbine/kernel/wave/scheduling/loop_reconstruction_utils.py
- iree/turbine/kernel/wave/scheduling/schedule.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention/attention.py
- lit_tests/kernel/wave/attention/attention_bias.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/evoformer.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/attention/pipelined_attention.py
- lit_tests/kernel/wave/attention/prefill_attention.py
- lit_tests/kernel/wave/gemm.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/evoformer_test.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/prefill_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/wave_e2e_test.py
- tests/kernel/wave/wave_gemm_test.py
- Set scheduling to be an enum option/param instead of bool S.T we can choose different strategies in the future
- Refactor loop_reconstruction to use num_stages and initiation_interval as opposed to scheduler to make it easy to pass heuristic based schedule in the future.
> [Wave] Refactor LoopConstructor infra to prep for heuristic base strat

- iree/turbine/kernel/lang/wave_types.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/global_to_shared_gathers.py
- iree/turbine/kernel/wave/hoisting.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention/decode_attention.py
- tests/kernel/wave/attention/paged_attention_test.py
Rewrite paged decode to get it closer to the triton kernel impl.
* Distribute K2 loop across splits, which requires custom `iters` and `start` on `TilingConstraint` as well as some custom masking code.
* Add `start` support to `TilingConstraint`
* `global_to_shared_gathers.py`: clone dependent read nodes instead of modifying exiting ones inplace, as they can be used by the other ops.
> [TKW] Paged decode attention rewrite

- .github/workflows/ci-tk.yaml
- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/promotion.py
- iree/turbine/kernel/wave/runtime/CMakeLists.txt
- iree/turbine/kernel/wave/runtime/runtime.cpp
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
- requirements.txt
- tests/kernel/wave/attention/extend_attention_test.py
This PR adds a custom wave runtime that can be used to launch kernels. The runtime uses nanobind to transfer the kernel arguments from Python to C++ and then launches the kernels using the hip API. In order to enable this, we add the C++ code for wave runtime and link against nanobind and torch to generate a shared library that can be loaded.
For this runtime, we need the hsaco binary instead of the vmfb. So we cache the hsaco and associated kernel launch info when the cache is enabled. Finally, we add a pass to compute the shared memory usage by summing up the bytes used by all the shared memory allocations.
This PR will require all old cache directories to be removed.
> [Wave] Add wave runtime

- iree/turbine/kernel/boo/conv_exports/__init__.py
- iree/turbine/kernel/boo/conv_exports/conv.py
- iree/turbine/kernel/boo/conv_exports/launch.py
- iree/turbine/kernel/boo/examples/conv_launchable.py
- iree/turbine/runtime/launch.py
- tests/runtime/launch_test.py
Adds a function to convert a `ConvSignature` into a `Launchable`, with added mlir and vmfb file caching/retrieval. 
Modifies `Launchable.jit_compile` to be able to optionally save and load jit-compiled artifacts within a directory.
> [BOO] Adds a function for getting a Launchable from a ConvSignature

- iree/turbine/kernel/wave/scheduling/graph_utils.py
- iree/turbine/kernel/wave/scheduling/prefetch_scheduling.py
- iree/turbine/kernel/wave/scheduling/resources.py
- iree/turbine/kernel/wave/scheduling/schedule.py
- iree/turbine/kernel/wave/scheduling/schedule_enums.py
- lit_tests/kernel/wave/gemm.py
- tests/kernel/wave/wave_gemm_test.py
This PR is a MVP/first bring up for a heuristics based scheduling strategy into Wave. In this PR, we introduce 2-stage prefetch scheduling (strategy currently only tested for GEMM).  Just for a brief recap, what we mean by 2 stage prefetch strategy is as such:
```
Convert vanilla schedule of:
for i = 0 to N:
a = READ_GLOBAL i
WRITE_SHARED a
barrier
b = READ_SHARED
COMPUTE b
into prefetch schedule:
a_0 = READ_GLOBAL 0
WRITE_SHARED a_0
for i = 0 to N - 1:
a_{i+1} = READ_GLOBAL i + 1
// a_{i+1} is NOT blocked by this barrier because barriers only block shared memory transfers
barrier
b_i = READ_SHARED
COMPUTE b_i
barrier
WRITE_SHARED a_{i+1}
barrier
b_N = READ_SHARED
```
In order to do that we needed to bring these changes:
1. Implement a scheduler class that generate a schedule and …
> [Wave] Add 2-stage prefetch scheduling strategy for GEMM

- tests/kernel/wave/attention/evoformer_test.py
- tests/kernel/wave/attention/extend_attention_test.py
failing on CI for non default path:
1. evoformer on MI250
2. C++ wave runtime
Signed-off-by: Stanley Winata <stanley.winata@amd.com>
> [Wave] temporarily turn off test for non default paths.

- iree/turbine/kernel/boo/conv_exports/conv.py
- iree/turbine/kernel/boo/conv_exports/launch.py
- iree/turbine/ops/conv_fwd.py
- tests/kernel/boo/conv_exports/implementations_test.py
This plugs in the `conv_2d_nhwc_fhwc` into a custom implementation for `ConvSignature.get_nn_module` to avoid generating unnecessary transposes. 
Some small additional fixes:
1. remove a debug print in the custom op generate method
2. fix an issue with disabling the boo_cache
3. adds the func op `preprocessing_pipeline` attr after lowering to iree-input (it appeared to be getting stripped).
Some examples of IR before vs. after these changes for the following signature (+/- `bias=True`) :
```python
ConvSignature(input_shape=[2,14,14,4], kernel_shape=[3,3,3,4], shared_layout="NHWC", dtype=torch.bfloat16)
```
are contained in this gist: <https://gist.github.com/zjgarvey/7d66d8ec6dc4470b22dd8329ed9e7e0a>
> [BOO] enable using `conv_2d_nhwc_fhwc` in conv exports

- .github/workflows/ci-tk.yaml
- docs/kernel/runtime.rst
- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/runtime/CMakeLists.txt
- iree/turbine/kernel/wave/runtime/setup.py
- iree/turbine/kernel/wave/wave.py
- requirements-wave-runtime.txt
- tests/kernel/wave/attention/extend_attention_test.py
Previously, the runtime needed a system wide install of rocm. We remove this constraint and instead use the torch libraries inside the torch pip package. Also, rather than build the wave-runtime during execution, we provide an option to pip install wave-runtime.
> [Wave] Build wave runtime using torch pip package

- iree/turbine/kernel/wave/compile_options.py
- iree/turbine/kernel/wave/profiling.py
- iree/turbine/kernel/wave/utils/run_utils.py
Recent refactors ignored the benchmarking code as it is not being captured by the builder. This PR updates the benchmarking code to reflect the new changes.
> [Wave] Restore benchmarking code

- iree/turbine/kernel/boo/conv_exports/README.md
- iree/turbine/kernel/boo/conv_exports/boo_driver.py
- iree/turbine/kernel/boo/conv_exports/conv.py
This adds a script for invoking convolutions through `boo`, mirroring the interface of `MIOpenDriver`.
The `-t 1` option to collect timing is implemented by launching the kernel in a subprocess, which is then traced using `tracy`. Using this requires:
- IREE runtime python bindings with tracy enabled. If using the pre-built `iree-base-runtime` package, this requires setting `IREE_PY_RUNTIME=tracy` in your environment
- `iree-tracy-capture`; see https://iree.dev/developers/performance/profiling-with-tracy/#building-the-tracy-capture-cli-tool
- `tracy-csvexport`; see https://iree.dev/developers/performance/profiling-with-tracy/#building-the-tracy-csvexport-tool
The script also supports reading a list of invocation commands from a file, through the `--commands-file` option. Each
line in the …
> [BOO] Add driver script for convolutions

- iree/turbine/kernel/wave/cache.py
- tests/kernel/wave/runtime/cache_test.py
Currently, we are caching nested function as freevars which is detected in getclosurevars. However we are only caching it's function pointer which means every time we have a nested function inside wave kernel, it will recompile every single time since it has a different function pointer.
Even worse, the kernel defintion that we have cached for these nested functions are often just something like:
```
@tkw.wave(constraints)
def base_attention(
q: tkl.Memory[B, N_Q, D_Q, GLOBAL_ADDRESS_SPACE, LOGIT_DTYPE],
k: tkl.Memory[B, N_KV, D_Q, ADDRESS_SPACE, LOGIT_DTYPE],
v: tkl.Memory[B, N_KV, D_KV, ADDRESS_SPACE, LOGIT_DTYPE],
c: tkl.Memory[B, N_Q, D_KV, GLOBAL_ADDRESS_SPACE, tkl.f32],
):
base_attention_core(q, k, v, c)
```
Which is very incomplete since we do not know what is inside …
> [Wave][Cache] Add caching support for nested functions

- iree/turbine/kernel/wave/runtime/CMakeLists.txt
This PR adds the copyright header to the wave runtime CMakeLists.txt.
> [Wave] Add missing header

- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
* Infer `elements_per_thread` for elementwise ops from tile size and num threads
* Some lit tests are not updated as they have suspicious `elements_per_thread` hardcoded
> [TKW] Infer `elements_per_thread` for elementwise ops

- iree/turbine/kernel/wave/layers/linear.py
- tests/kernel/wave/layers/wave_linear_test.py
- Implement Wave kernel for linear with bias add by fusing it into the init_reg for the mma accumulator.
- Refactoring function getter to enable both bias and non-bias
- Remove element per thread from kernel since PR landed to not require explicit setting of that anymore.
> [Wave] Implement fused bias-add on Wave kernel Linear Layer

- iree/turbine/kernel/wave/codegen/emitter.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
* It was used to workaround upstream issues, but looks like they are fixed
* Disable it but keep the code around for the future.
> [TKW] Disable ceildiv emulation

- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/utils/general_utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- tests/kernel/wave/wave_e2e_test.py
* If we kernel doesnt have `mma`s but have reduce ops use them to determine ops indexing.
* `tkw.WorkgroupConstraint(N, N, 0)` hack is no longer needed as reduce nodes inside reduction loop will automatically distributed across threads.
* Fix `test_toy_online_softmax` for unaligned shapes.
* Refactor constraints and introduce `DistributionConstraint` base class.
> [TKW] Propagate index from reduce nodes

- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
This PR uses reciprocals instead of divs to
compute the logits faster.
> [Wave] Use reciprocal to compute softcap logits

- iree/turbine/kernel/wave/templates/quantized_attention.py
- lit_tests/kernel/wave/attention/quantized_attention.py
Currently, there is a line that shifts the tensors before softmax quantization, however that is effectively a no-op.
With this change, the value quantized to FP8 are correctly rescaled from the range [0, 1] to [0, 240] before quantization, thus using more the fp8 value range.
We need to undo the rescaling at the end before the output is returned.
cc @raikonenfnu @KyleHerndon
> Feat: better scaling for fp8 quant

- .github/workflows/ci-tk.yaml
- tests/conftest.py
- tests/kernel/wave/attention/backward_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/common/utils.py
* Print slowest tests on CI and skip the worst offenders (some of them were taking 300+sec).
* Reduced mi300 test time 18min -> 11min
* Let's keep individual tests on CI under 1min, everything else goes into `expensive_tests`
> [TKW] Skip slow tests

- iree/turbine/kernel/wave/templates/gqa_vanilla_attention.py
- iree/turbine/kernel/wave/templates/quantized_attention.py
- iree/turbine/kernel/wave/utils/torch_utils.py
- tests/kernel/wave/attention/gqa_vanilla_attention_test.py
- tests/kernel/wave/attention/quantized_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/common/shapes.py
- tests/kernel/wave/common/utils.py
This PR creates a new template for GQA/MQA vanilla attention that supports both causal masks and sliding windows for both f16 and f8 datatypes.
> [Wave] Add GQA/MQA Vanilla template

- iree/turbine/kernel/boo/conv_exports/README.md
- iree/turbine/kernel/boo/conv_exports/boo_driver.py
This adds some extra options to `boo_driver.py`:
- `--csv <file>`: this outputs timing info in csv format to the specified file
- `--splat-input-value <val>`: this uses splat inputs instead of the default random values
Additionally the script now continues if the traced invocation fails, so that all specified configurations are reported.
I've also documented a workaround I'm using to get tracing working with locally built python bindings. Using this requires a recent commit of IREE: iree-org/iree#20448
> [boo_driver] Add `--csv` and `--splat-input-value` options

- iree/turbine/kernel/wave/layers/quant_linear.py
- iree/turbine/kernel/wave/utils/general_utils.py
- tests/kernel/wave/layers/wave_quant_linear_test.py
Adds a quantized linear layer kernel and its test. Only supports per-tensor quantization currently and is tested for `fp8` datatype, however this can be used to extend to other types as well.
> [Wave] Add quantized linear layer kernel

- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
Adds custom causal mask for Extend Attention. Mask has flattened bool values of `seq_len_extend, seq_len_prefix` for each sequence. Sequence demarcation is identified by the `mask_offsets`.
> [Wave] Add custom causal mask for Extend Attention

- iree/turbine/kernel/_support/location.py
- iree/turbine/kernel/compiler/host_codegen.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/compile.py
- iree/turbine/kernel/wave/compile_options.py
- lit_tests/kernel/wave/location.py
Representing and propagating file/line location information from Python kernel source significantly improves debugging experience.
Note that column information is only available since Python 3.11 so additional logic is added to handle older versions.
> Capture location information from Python

- iree/turbine/kernel/wave/nn/functional/quant_attention.py
- tests/kernel/wave/nn/functional/wave_quant_attention_test.py
Address comments from previous PR https://github.com/iree-org/iree-turbine/pull/708 with respect to adding causal test and exposing fp8 type api.
> [Wave] Add is_causal test and plumb quant_dtype into API.

- iree/turbine/kernel/boo/examples/resnet_18_backward.py
- iree/turbine/kernel/boo/modeling/replace.py
- tests/kernel/boo/modeling/boo_conv_2d_test.py
In particular, this should allow setting `model = model.to(memory_format=torch.channels_last)` to enable `NHWC` convolutions, whereas previously we had been forcing these tensors back to `NHWC` format by calling `contiguous()` on the inputs inside the `Launchable` call. 
Tests are added to check if `BooConv2d` is calling into the expected kernel signatures.
> [BOO] allow `BooConv2d` to take advantage of non-contiguous memory formats

- iree/turbine/kernel/wave/cache.py
This commit restores the import math statement that was unintentionally removed as part of #677. The missing import caused runtime errors in grid_fn.
> [Wave] Fix missing math import introduced in #677

- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
- requirements-iree-pinned.txt
AMDGPU shuffles only support i32 internally and all other datatypes need to be bitcasted/zexted/repacked to multiple values. Instead of doing this on Wave side (which was incomplete anyway), rely on upstream repacking during GPU->ROCDL lowering, which was recently added.
This requires latest IREE so it's a breaking change.
> [TKW] Use uptream `gpu.shuffle` repacking

- iree/turbine/kernel/wave/constraints.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
Currently most non-MMA test cases uses 1 warp, but once we go over 1 warp this will break, as we are using block threadIdx.x instead of using laneIdx. This will be problematic because linearized access pattern looks something like:
```
blockIdx.x * blockDim.x + waveIdx.x * waveDim.x + threadIdx.x
```
In case above threadIdx.x will go over the entire dimension of thread in the blockDimension, but this should already be accounted for from the waveIdx.x * waveDim.x, hence will cause out of bound/unexpected behaviour. This PR essentially changes the threadIdx.x into laneIdx.x which is threadIdx.x // threads_per_wave.
> [Wave] fix read/write index to use laneIdx

- iree/turbine/kernel/boo/conv_exports/boo_driver.py
We don't care about the actual values, so set the print threshold to `0` so they're always hidden.
> [boo] Fix boo_driver sometimes printing result values

- iree/turbine/aot/support/ir_utils.py
- iree/turbine/kernel/_support/dtype.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
- Refactor conversion op as a util/helper function S.T we can reuse for ScalarOp handler.
- Add support for inferType on ComparisonPyOp on Scalars
- refactor dtype of DataType to be self which is what is expected and can support all dtypes.
- Implement NewScalarOp and handlers
> [Wave] Implement NewScalar op support

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/utils/graph_utils.py
- iree/turbine/kernel/wave/utils/mma_utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/iteration.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/multi_buffering.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/scheduling_test.py
- tests/kernel/wave/visualization_test.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds support for init args in the while loop style iterate ops. In order to accomplish this, a couple of changes had to be made
1. Moving add_get_results out from an expansion specific pass to one before the infer types pass
2. Fixing indices of MMA and ACC nodes during index propagation
3. Updates to handler. Specifically since the while loop returns the value of the induction variable while we don't expose this in the DSL, we reorder the arguments.
4. Changes to lit tests to fix this
5. Updates to logic to determine MMA reduction dims and added validation to avoid ambiguities
> [Wave] Add support for init args in while loops

- iree/turbine/kernel/compiler/host_codegen.py
- iree/turbine/kernel/wave/compile.py
- lit_tests/kernel/wave/attention/attention.py
Plumbs func_name through to the IR creation of `isolated_test_call` instead of hard-coding it to "isolated_benchmark".
> [Wave] Plumb func_name into compile.py for wave asm

- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/lang/global_symbols.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/analysis/partition_strided_operators.py
- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/expansion/expansion_utils.py
- iree/turbine/kernel/wave/hoisting.py
- iree/turbine/kernel/wave/templates/speculative_decoding.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/speculative_decoding.py
- tests/kernel/wave/speculative_decode_test.py
- tests/kernel/wave/type_inference_test.py
This PR adds the first part of the speculative sampling kernel implemented in Wave. Multiple changes had to be made to produce a functional kernel, such as 
- Handling of multiple iterates 
- Adding support for sympy.Eq, invert operator
- Improvements to expansion 
- Making hoisting aware of setsymbols so that if a read has a mapping that uses a symbol that is being set, dont hoist the read before the setsymbol
> [Wave] Add first speculative sampling kernel

- iree/turbine/kernel/wave/nn/functional/__init__.py
- iree/turbine/kernel/wave/nn/functional/attention.py
- iree/turbine/kernel/wave/templates/vanilla_attention.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/nn/functional/wave_sdpa_test.py
- tests/kernel/wave/runtime/cache_test.py
This PR adds a wave_sdpa API that is similar to the Pytorch API. Internally, it utilizes the vanilla attention template to get the kernel. 
The template was modified to do the scaling inside the kernel so that the query matrix no longer has to be scaled outside the kernel. This was modified in all the users of the vanilla template.
> [Wave] Add wave_sdpa API for f16 attention

- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/templates/vanilla_attention.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/common/shapes.py
Adds batch_size field to AttentionShape to not have to flatten batch and num head dims for BHSD kernel.
> [Wave] Add batch_size field to AttentionShape

- iree/turbine/kernel/wave/perf/benchmark.py
- iree/turbine/kernel/wave/perf/benchmark_configs.json
- tests/kernel/wave/attention/vanilla_attention_test.py
This PR creates a benchmark script for wave sdpa. It takes in a json file and benchmarks it using rpdtrace.
The command is 
```
python iree/turbine/kernel/wave/perf/benchmark.py --config iree/turbine/kernel/wave/perf/benchmark_configs.json --num_warmup 0 --num_iterations 1
```
> Enable benchmarking in performance ci

- iree/turbine/kernel/wave/expansion/expansion.py
Demote it from warning to info (which is not printed by default)
> [TKW] Silence expansion warning

- setup.py
Boo use was broken in pip install because the tuning spec file wasn't included.
> [BOO] Include tuning specs in pip package

- iree/turbine/runtime/device.py
- iree/turbine/support/conversions.py
- tests/runtime/device_test.py
Interop for BF16 / FP8 requires some munging to bypass numpy's lack of support. In these cases we bitcast the underlying tensor and use the integer equivalent bitwidths
> Add support for additional type interop

- .github/workflows/ci-tk.yaml
- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/compile.py
- iree/turbine/kernel/wave/utils/run_utils.py
- iree/turbine/kernel/wave/wave.py
- tests/conftest.py
Even if caching is disabled, we are using cache dir for the wave_runtime and hsaco files.
Assign each worker an unique dir to avoid race conditions.
> [TKW] Avoid cache folder race conditions when running tests in parallel

- iree/turbine/kernel/boo/conv_exports/boo_driver.py
Minor fix to the driver option, it should be called `--time`, not `--timing`:
https://github.com/ROCm/MIOpen/blob/936ebca2aa08a60f629f757bdc0f1f66e1f8d95c/driver/conv_driver.hpp#L938
> [boo_driver] Align `-t` option name with miopen driver

- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- lit_tests/kernel/wave/attention/decode_attention.py
- tests/kernel/wave/attention/paged_attention_test.py
Make `kv_lens` and `num_seqs` args of the Paged Decode kernel dynamic, so they won't trigger the recompilation.
> [TKW] Paged Decode dynamic symbols

- iree/turbine/kernel/boo/conv_exports/boo_driver.py
Renaming `timing` to `time` resulted in throwing an error when trying to access `timing_args.timing`.
> [BOO] Fix a bug in `boo_driver.py` resulting from arg rename

- iree/turbine/kernel/boo/conv_exports/tuning_specs.mlir
This adds tuning configurations for the following driver commands (mostly group convs), reducing execution time by 10-70%:
```
convbfp16 -n 2 -c 896 -H 59 -W 91 -k 896 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 16 -F 1 -t 1  
convbfp16 -n 2 -c 448 -H 118 -W 182 -k 448 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 8 -F 1 -t 1 
convbfp16 -n 2 -c 224 -H 470 -W 725 -k 224 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 4 -F 1 -t 1 
convbfp16 -n 2 -c 448 -H 235 -W 363 -k 448 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 8 -F 1 -t 1 
convbfp16 -n 2 -c 896 -H 118 -W …
```
> [boo] Add more tuning configurations

- iree/turbine/kernel/wave/memory_analysis/minimize_shared_allocs.py
This PR adds an additional check that the alloc
is in shared memory before optimizing it.
> [Wave] Add additional check when minimizing allocs

- iree/turbine/kernel/boo/ops/conv.py
- tests/kernel/boo/ops/boo_conv_test.py
This enables running lower-precision forward and backward kernels when performing the forward pass of a model in a `torch.amp.autocast` context.
> [BOO] Add autocast functionality to `boo_conv`

- iree/turbine/runtime/device.py
Adds code similar to <https://github.com/iree-org/iree-turbine/blob/d71316265c73c2d0c8487e1d98ca69a94d7a107c/iree/turbine/kernel/wave/utils/run_utils.py#L104>
There seems to be an issue with memory not getting freed when the py capsule for a dlpack tensor gets renamed. 
I filed an issue in iree: <https://github.com/iree-org/iree/issues/20849>, but in the meantime, we need this fix in order to do basically anything for BOO without running out of memory.
> [runtime] Rename dltensor capsule to avoid memory leak

- iree/turbine/kernel/_support/tracing.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/barriers.py
- iree/turbine/kernel/wave/decompose_reduce_ops.py
- iree/turbine/kernel/wave/scheduling/loop_reconstruction.py
- iree/turbine/kernel/wave/utils/graph_utils.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/gemm.py
- lit_tests/kernel/wave/iteration.py
- lit_tests/kernel/wave/minimize_global_loads.py
This PR has two main purpose.
First and most importantly, it teaches our compiler to only insert shared memory barriers when there is truly no barriers in between ops. This was assumed before but with the soon-coming PR of ping-pong where we re-order and want barriers to be precisely inserted, this PR help handles those case and to not accidentally insert too many barriers when not needed.
Secondly, and complimentarily, this PR teaches compiler to insert barrier between ops from different iterations. Most commonly, shared_read at time=t, and shared_write at time=t+1. This allows us to also remove the hardcoded insertion of barrier at the start of every Iterate subgraph. For pingpong, this will allow the PingPong pass to manually insert barriers for next iteration, and this pass can …
> [Wave] Generalize Barriers to work across iterations

- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/compile.py
- iree/turbine/kernel/wave/runtime/runtime.cpp
- iree/turbine/kernel/wave/utils/run_utils.py
- iree/turbine/kernel/wave/wave.py
- tests/conftest.py
There are multiple changes here:
* Previously calling to `wave_compile` multiple times with `wave_runtime=True` was broken as  `wave_compile`  were overwriting serialized gpu binary on disk. Fixed by moving binary reading into `WaveKernel` init from the invoke.
* Simplified `wave_runtime.cpp` and `invoke_with_wave_runtime` and removed all the caching logic from there as it moved to `WaveKernel`.
* Use `tempfile.TemporaryDirectory()` for the temp bin path so it will be unique for each process to reduce race conditions when Wave called from multiple processes (races are still possible, though, when copying binary into cache dir).
* HIP module lifetime is now bound to `WaveKernel` lifetime.
* `get_wave_runtime_dir()` is no more
> [TKW] Improve wave runtime

- iree/turbine/kernel/boo/conv_exports/conv.py
- iree/turbine/kernel/boo/examples/resnet_18_backward.py
- iree/turbine/kernel/boo/ops/conv.py
- tests/kernel/boo/modeling/boo_conv_2d_test.py
- tests/kernel/boo/ops/boo_conv_test.py
This change uses a `torch.library.custom_op` to define `boo_conv` instead of `autograd.Function`, which enables `torch.compile` for models with boo convolution. In addition, this commit factors out the autocasting logic since the decorators don't behave very well with respect to `custom_op`. It also changes the behavior slightly to mimic the functionality of `torch.convolution` under autocast contexts. 
These changes are a temporary solution, since it will be beneficial to take a more systematic approach of implementing autograd custom ops. I think this will make the most sense via implementing `iree.turbine.runtime.CustomOp` autograd support. Ideally, boo convolutions can simply be an application of `CustomOp` eager execution, in such a way that this is compatible with backward, …
> [BOO] Enable `torch.compile` for models with boo convs

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- lit_tests/kernel/wave/gemm.py
- tests/kernel/wave/wave_gemm_test.py
This patch fixes a bug in the `transform_index` method in `Permute`. The bug occurred when a batch dimension was permuted, and the indices came from an MMA. In this particular case the strides shouldn't get permuted, only the indices.
Below is a reproducer of the bug, where before the fix the write would use incorrect strides.
```python
@tkw.wave(constraints)
def batched_gemm_with_permute(
a: tkl.Memory[B, M, K, ADDRESS_SPACE, tkl.f16],
b: tkl.Memory[B, N, K, ADDRESS_SPACE, tkl.f16],
c: tkl.Memory[M, B, N, ADDRESS_SPACE, tkl.f32],
):
c_reg = tkl.Register[B, M, N, tkl.f32](0.0)
@tkw.iterate(K, init_args=[c_reg])
def repeat(
acc: tkl.Register[B, M, N, tkl.f32],
) -> tkl.Register[B, M, N, tkl.f32]:
a_reg = tkw.read(a, elements_per_thread=LOAD_ELEMS_PER_THREAD)
b_reg = tkw.read(b, …
```
> [wave] Fix bug in `Permute.transform_index`

- requirements-iree-pinned.txt
We have a bad regression in Wave between `3.5.0rc20250516` and `3.5.0rc20250517`. 40% perf drop in paged extend attention kernel and crash in paged decode (which is not reproducible in our unit tests).
I'm locking to the last known good version until further investigation.
> Pin IREE version to 3.5.0rc20250516

- iree/turbine/kernel/wave/iree_utils.py
- iree/turbine/kernel/wave/nn/linear.py
- iree/turbine/runtime/launch.py
- tests/kernel/wave/attention/chained_gemm_test.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/wave_e2e_test.py
- tests/kernel/wave/wave_gemm_test.py
`generate_iree_ref` only used to get reference values for Wave tests and it also the last user of `inplace=False` flag in Wave.
> Use `turbine.runtime` for `generate_iree_ref`

- iree/turbine/kernel/boo/ops/conv.py
- tests/kernel/boo/modeling/boo_conv_2d_test.py
- tests/kernel/boo/ops/boo_conv_test.py
This is temporarily set as defaulting to "do not use backward boo kernels" as our performance on many backward convs is not competitive.
> [BOO] Add an env variable for toggling backward boo convolutions

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/codegen.py
Add a new `softsign` kernel variant that replaces the previous `tanh_approx` implementation. Benchmarks show a 10~15% speedup over `tanh_approx`, but with a modest accuracy drop (e.g. Grok performance falls from ~83% to ~79%). This commit provides the softsign implementation alongside existing approximations for users to choose the appropriate tradeoff.
> [Wave] Introduce softsign kernel to replace tanh_approx

- iree/turbine/kernel/wave/templates/speculative_decoding.py
- lit_tests/kernel/wave/speculative_decoding.py
- tests/kernel/wave/speculative_decode_test.py
1. refactored variable names to be in sync across speculative decode and speculative sampling kernels
> [Wave] Align variable names in speculative decode kernel

- iree/turbine/kernel/wave/common/utils.py
- iree/turbine/kernel/wave/utils/reference_kernel_utils.py
- tests/kernel/wave/attention/gqa_vanilla_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/common/utils.py
- tests/kernel/wave/nn/functional/wave_quant_attention_test.py
- tests/kernel/wave/nn/functional/wave_sdpa_test.py
This PR moves `scaled_dot_product_attention_bhsd` under iree.turbine to have one util file for all the reference kernels.
> Move scaled_dot_product_attention_bhsd under iree.turbine

- iree/turbine/kernel/wave/scheduling/graph_utils.py
Make `aplp_lib` lib import local.
It is optional in current scheme of things and we shouldn't emit warning if user is not using it, with local import is it will be imported only if it actually being used.
(Also, users will get a proper import error instead of warning + random "unknown symbol `compute_aplp`")
Fixes https://github.com/iree-org/iree-turbine/issues/897
> [Wave] Hide APLP warning

- iree/turbine/kernel/boo/ops/conv.py
- tests/kernel/boo/modeling/boo_conv_2d_test.py
- tests/kernel/boo/ops/boo_conv_test.py
Small bugfix for the case when a channels-last conv doesn't need one of input/weight gradients computed.
Also adds setter functions for turning on and off boo backward convolution kernels from python to enable testing both paths.
> [BOO] don't permute `None` in pytorch convolution backward

- iree/turbine/kernel/_support/indexing.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/analysis/partition_strided_operators.py
- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/codegen/read_write.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/expansion/expansion_utils.py
- iree/turbine/kernel/wave/shared_memory_indexing.py
- iree/turbine/kernel/wave/utils/general_utils.py
- iree/turbine/kernel/wave/utils/symbol_utils.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/gemm.py
- tests/kernel/wave/wave_gemm_test.py
Handle `tile_size < vector_size` case by doing masking on shared mem. For the case when we have `BLOCK_M x BLOCK_N` tile size and `VEC_M x VEC_N` vector shape, it will read `BLOCK_M x BLOCK_N` tile from global to shared mem and then read   `VEC_M x VEC_N` from shared mem, masking values outside of `BLOCK_M x BLOCK_N`  to zeros.
* Refactor `DistributionConstraint` to have `get_index_bound` which will return combined global bound and tile bound and use it to determine bounds.
* Remove old hacky `align_index_sizes` pass, handle shared mem logic directly in `_build_mask` during MLIR lowering.
* Fix `sympy.Min/Max` lowering when the have more then 2 args.
> [Wave] Add support for WG/Wave tiles smaller than vector sizes

- iree/turbine/kernel/lang/wave_types.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- iree/turbine/kernel/wave/utils/general_utils.py
- tests/kernel/wave/attention/paged_attention_test.py
* Separate `K2` symbol into  `SPLIT_ITER` and `KV_LENS`, `SPLIT_ITER` is used for reduction iter and masking calculation and `KV_LENS` is actual input tensor size.
* Move `KV_START_IDX` inside the masking constraint and set `tkw.set_symbol(SPLIT_ITER, seq_length)` inside the kernel to properly update masking bounds for current split.
* Update tests and ref code to test non-uniform `kv_lens_tensor`/`request_indices` sizes.
* Depends on https://github.com/iree-org/iree-turbine/pull/906 for the  case `NUM_Q_HEADS / NUM_KV_HEADS < 16`
> [TKW] Update decode

- iree/turbine/kernel/boo/conv_exports/boo_driver.py
- default to only using a single GPU, instead of all of them. `--gpu-id=-1` will use all GPUs.
- use a random tracy port to avoid conflicts
> [boo] Make `boo_driver` friendlier for shared machines

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- lit_tests/kernel/wave/codegen.py
This is a simple PR that introduces bitcastOp into wave. Bitcating is very useful to represent or pack data from different bitwidths. Currently bitcastOp only support bitcast for same bitwidth. In follow on PRs, we will add support for scaled dimension and bitcasting to different widths.
> [Wave] Implement BitcastOp

- iree/turbine/kernel/boo/conv_exports/tuning_specs.mlir
Adds addition tuning configs. On MI300X this results in the following speedups:
```
convbfp16 -n 128 -c 384 -H 24 -W 48 -k 384 -y 3 -x 1 -p 1 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 3 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100    -49.56 (-25.4%)
convbfp16 -n 128 -c 384 -H 24 -W 48 -k 512 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100    -59.14 (-29.0%)
convbfp16 -n 16 -c 13 -H 225 -W 225 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100    -300.66 (-65.7%)
convbfp16 -n 16 -c 194 -H 24 -W 16 -k 192 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --in_layout NHWC --out_layout NHWC …
```
> [boo] Even more tuning configurations

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/codegen/read_write.py
- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/expansion/expansion_utils.py
- iree/turbine/kernel/wave/minimize_global_loads.py
- iree/turbine/kernel/wave/utils/general_utils.py
- iree/turbine/kernel/wave/utils/mapping_utils.py
- lit_tests/kernel/wave/gemm.py
- tests/kernel/wave/wave_gemm_test.py
This a first PR in a series of PR that will ultimately add sub-byte matmul support on Wave. This PR specifically gives our compiler the capability to handle "scaled" dimensions which will be useful for representing for example MxKxF4 -> Mx(K/2)xI8 or on our current tests packed MxKxF16 -> Mx(K/2)xI32. 
To accomplish the above, we added these following changes:
1. Teach read/write to handle type with scales (M, K/2). Letting indexing_dims of read/write use infer_dim to get `K` from scaled expr `K/2`. Moreover, then we teach infer_type of read/write to map these dimensions into it's scaled type (e.g K -> K/2), this is important for read/write with mapping/transpose.
2. Enable BitcastOp handle scale_factor != 1. We already have this implemented in a previous PR but artificially blocked it …
> [Wave] Teach compiler to handle "scaled" dimensions/indexing

- iree/turbine/kernel/wave/scheduling/loop_reconstruction.py
The pipelining of a reduction graph creates a new reduction node and a corresponding subgraph. 
The old reduction node is erased, but its subgraph stays in the trace and also shows up during printing of the trace.
This removes the old unused subgraph
> [Wave] NFC: Remove superfluous reduction subgraph after pipelining

- iree/turbine/kernel/boo/modeling/replace.py
- iree/turbine/kernel/boo/ops/__init__.py
- iree/turbine/kernel/boo/ops/conv.py
- iree/turbine/kernel/boo/ops/layout_customizable_conv.py
- iree/turbine/kernel/boo/ops/utils.py
- tests/kernel/boo/modeling/boo_conv_module_test.py
- tests/kernel/boo/ops/boo_conv_test.py
Although mostly a feature of using pytorch backward convs, it is advantageous to move `torch.permute` calls inside the custom op body, since the backward call for pytorch needed to permute all of  `x, w, grad_output, grad_input, grad_weight`.
E.g., running the resent 18 example, the second boo conv forward takes approximately the same time with/without these changes (~330us); however the backward call takes 533us instead of 710us, which saves a significant chunk of CPU time.
It may eventually be a good idea to figure out how to manage this better during the dlpack handoff instead of needing to explicitly permute the tensor from `torch.channels_last` "NCHW" to contiguous "NHWC".
1. The op `boo_convolution` and `boo.convolution_backward` are modified to no-longer accept explicit layout …
> [BOO] Reduce some additional cpu overhead

- iree/turbine/kernel/wave/codegen/emitter.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/gemm.py
- lit_tests/kernel/wave/mma.py
We want kernel code to use 100% upstream dialects eventually.
> [Wave] Use `gpu.block_id`

- iree/turbine/kernel/_support/tracing.py
- iree/turbine/kernel/compiler/dispatch_codegen.py
- iree/turbine/kernel/compiler/host_codegen.py
- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/lang/__init__.py
- iree/turbine/kernel/lang/wave_types.py
- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/compile.py
- iree/turbine/kernel/wave/runtime/runtime.cpp
- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/templates/extend_attention_rpe.py
- iree/turbine/kernel/wave/utils/graph_utils.py
- iree/turbine/kernel/wave/utils/run_utils.py
- iree/turbine/kernel/wave/wave.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/wave_e2e_test.py
I'm planning to retire `dynamic_symbols_map` eventually and extract symbol values directly from the input tensor dimensions. One exception is `extend_attention` which have `MAX_EXTEND_SEQ_LEN` symbol which does not correspond to any input tensor dimension.
As we now support scalar codegen, instead of using `dynamic_symbols_map` we now can just pass `MAX_EXTEND_SEQ_LEN` directly as kernel argument.
Extend attention is using `MAX_EXTEND_SEQ_LEN` for grid dimension calculation so normal scalar + `set_symbol` won't work. Instead, introduce `SymbolBind` annotation, which works exactly like scalar arg, but also immediately binds value to the corresponding symbol.
Most of the codegen changes are to propagate scalar args to the dispatch dims and to generally support scalar args in iree runtime …
> [TKW] Allow to bind symbols from the scalar arguments

- iree/turbine/kernel/wave/templates/vanilla_attention.py
- tests/kernel/wave/attention/vanilla_attention_test.py
This PR is to make the N (head size kv) dimension static and H (num_heads) dimension dynamic and changes the order of the dynamic dims to B, H, M, K2, so the index arguments for the dynamic dimensions are based on the order of the inputs.
> Make B, H, M, K2 dynamic dims in bhsd_attention kernel

- lit_tests/lit.cfg.py
- tests/conftest.py
- disable caching for pytest by default
- always disable caching for lit
The usual way of disabling the tests does not work for lit:
```sh
WAVE_CACHE_ON=0 lit lit_tests/ -v
```
> [Wave] Disable cache for pytest and lit by default

- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- tests/kernel/wave/attention/paged_attention_test.py
Can be derived from `shape.num_query_heads == shape.num_kv_heads`, no need for user to specify.
> [Wave] Remove `mha` param from paged decode attention

- docs/core/runtime.rst
- docs/index.rst
- docs/wave/aplp.rst
- docs/wave/fused_softmax.rst
- docs/wave/gemm_tutorial.rst
- docs/wave/getting_started.rst
- docs/wave/minimize_global_loads.rst
- docs/wave/pingpong_reordering.rst
- docs/wave/schedule.rst
- docs/wave/schedule_modifier.rst
- docs/wave/shared_memory.rst
- docs/wave/system_architecture.rst
- docs/wave/wave.rst
This PR moves all the wave docs under the top level wave.rst file. It also fixes compile time warnings.
> [Wave] Fix documentation formatting

- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- lit_tests/kernel/wave/attention/decode_attention.py
Distribute across `head_size_kv` instead of `num_query_heads` for low `num_query_heads` to get threads better utilized.
Gave around 85->87 tok/s improvement on e2e bench 
```
NUM_Q_HEADS, NUM_KV_HEADS, HEAD_SIZE, HEAD_SIZE_KV, NUM_SEQS 
(6, 1, 128, 128, 1)
```
> [Wave] Change paged decode attention stage 2 distribution.

- iree/turbine/kernel/wave/generate_bounds_exprs.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- lit_tests/kernel/wave/attention/decode_attention.py
Add ability to override mask expression for read/write op. Bounds/masking expressions are usually generated by `generate_bounds_exprs` pass, ignore the op if it has bounds expr already set. Bounds exprs have format `{A: A_BOUND, B: B_BOUND, ...}` and setting it to empty dict will make mask always true.
Paged decode second stage U iterator is always smaller than U bounds, so force the non-masked read op until we have a better analysis.
> [Wave] Force non-masked ops in decode second stage

- iree/turbine/dynamo/backends/boo.py
- iree/turbine/kernel/boo/examples/subgraph_extraction.py
- iree/turbine/kernel/boo/fusion/apply.py
- iree/turbine/kernel/boo/fusion/subgraph.py
- iree/turbine/kernel/boo/ops/graph.py
- setup.py
- tests/kernel/boo/fusion/subgraph_fusion_test.py
- tests/kernel/boo/ops/graph_ops_test.py
This changes the `boo` fusion code to integrate a `torch.compile` backend that runs after AOTAutograd. This greatly simplifies things on our end, since pytorch now:
- handles capturing the forward and backwards passes, and provides these to us as separate graphs for compilation
- identifies values in the forwards pass that are required in the backwards pass, making them explicit outputs of the forward graph
- recompiles the graph as necessary, e.g. due to input shape changes
closes #1037, #1014
> [boo] Integrate boo fusion as a `torch.compile` backend

- iree/turbine/kernel/wave/compile_options.py
- iree/turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_e2e_test.py
This gives the option a default level of 2, and disables optimization passes for optimization level 0.
> [Wave] add optimization_level compile option

- iree/turbine/kernel/wave/expansion/expansion_utils.py
- iree/turbine/kernel/wave/utils/general_utils.py
- lit_tests/kernel/wave/attention/decode_attention.py
- tests/kernel/wave/attention/paged_attention_test.py
There were 2 issues:
* Expansion was generating less nodes than needed when dim size is not divisible by vector size
* Masking code wasn't generating properly for non-trivial vector sizes when corresponding dimension is not part of the constraints.
> [Wave] Fix paged decode attention for weird head sizes

- iree/turbine/kernel/wave/README.md
Progress on https://github.com/iree-org/iree-turbine/issues/1055.
See the new repository at https://github.com/iree-org/wave.
> Add announcement about iree/turbine/kernel/wave code moving.

- setup.py
This file was moved a while ago, so boo has just been silently broken unless installed from a cloned repo.
I'd like to find a way to test this soon, but we need to fix this immediately.
> [BOO] Fix setup for tuning specs path

- iree/turbine/dynamo/backends/boo.py
- iree/turbine/kernel/boo/fusion/apply.py
- iree/turbine/kernel/boo/fusion/replacement.py
- iree/turbine/kernel/boo/fusion/schema.py
- iree/turbine/kernel/boo/ops/conv.py
- iree/turbine/kernel/boo/ops/graph.py
- iree/turbine/transforms/general/custom_op_expansion.py
- tests/kernel/boo/fusion/integration_test.py
This adds the functionality for doing `1-1` op replacements after subgraph fusion. By default we replace `aten.convolution` with our custom convolution op.
> [boo] Replace aten.convolution with boo convolution

- iree/turbine/kernel/boo/fusion/apply.py
- iree/turbine/kernel/boo/fusion/schema.py
- iree/turbine/kernel/boo/fusion/subgraph.py
- tests/kernel/boo/fusion/subgraph_fusion_test.py
Enables specifying whether to make a single dispatch for subgraphs extracted based on the `OpFusionSpec` in a `FusionSchema`.
> [BOO] Enable `make_single_dispatch` specification in `FusionSchema`.

- iree/turbine/kernel/boo/ops/graph.py
- tests/kernel/boo/ops/graph_ops_test.py
Since we are doing AOT graph fusion, the graph ops we insert do not need to specialize based on memory format or shapes at runtime.
This adds some comments, factors out some useful layout management utilities, and moves layout inference and name getting outside the op implementation.
Something to consider:
Although it should be possible to get the `Launchable` itself ahead-of-time, it's a bit subtle since the example args we get from the source graph module are in a fake mode which is specific to the existing dynamo context of `torch.compile`. There might be some way to locally disable the existing dynamo/fake_mode context for the `get_launchable` sample args, but I figure we could address this in a follow-up.
At least the `get_launchable` call during runtime should really just be looking …
> [BOO] Clean up graph op implementation

- iree/turbine/kernel/boo/conv_exports/conv.py
- iree/turbine/kernel/boo/ops/conv.py
- iree/turbine/kernel/boo/ops/layout_customizable_conv.py
- iree/turbine/kernel/boo/ops/utils.py
Almost the same logic for generating function names was present in two different locations, creating room for divergence and bugs.
> [boo] deduplicate get_func_name for convolutions

- iree/turbine/kernel/boo/README.md
This adds information about the boo `torch.compile` backends and removes information about the convolution-specific replacement utility.
> [BOO] Update README with torch.compile information

- tests/kernel/boo/driver/cache_prepopulator_test.py
The temporary directory override has accidentally creeped in with a larger commit.
> [boo] remove debug logic leftover

- iree/turbine/kernel/boo/op_exports/conv.py
The separation was necessary primarily for serialization purposes and there are now other mechanisms to support that. This also improves property discovery by no longer proxying to the storage object via `__getattr__` that was confusing the language server.
> [boo] fold ConvSignatureStorage into ConvSignature

- iree/turbine/aot/params.py
avoids user error like trying to use `save_module_parameters("my_mod.safetensors", myModule)`
> enforce irpa extension on save

- iree/turbine/kernel/boo/runtime/cache.py
- tests/kernel/boo/conftest.py
- tests/kernel/boo/driver/cache_prepopulator_test.py
- tests/kernel/boo/fusion/integration_test.py
- tests/kernel/boo/fusion/subgraph_fusion_test.py
- tests/kernel/boo/modeling/boo_conv_module_test.py
- tests/kernel/boo/ops/boo_conv_aot_test.py
- tests/kernel/boo/ops/boo_conv_test.py
- tests/kernel/boo/ops/graph_ops_test.py
This adds a `boo_cache_dir` pytest fixture, which enables the file cache in a test-local directory for the duration of the test, and returns the path so that the test can inspect the contents. This avoids each test needing to set up its own temporary directory. A following change will turn off the file cache by default, so only tests that explicitly request `boo_cache_dir` (or turn on the cache internally) will have file caching enabled.
A change in behaviour here is that the cache is left intact after test execution finishes, which allows for easier debugging. By default pytest dumps test files under `/tmp/pytest-of-$USER/pytest-current/`
This also adds an `autouse` fixture which sets the BOO cache directory to a test-local directory, in order to isolate tests from each other.
> [boo] Add a pytest fixture for enabling the file cache

- iree/turbine/kernel/boo/README.md
- iree/turbine/kernel/boo/runtime/cache.py
The file cache has limited usefulness outside of testing/debugging, and is error-prone for users/developers as we don't have a good system for automatically invalidating it.
> [boo] Disable file caching by default

- iree/turbine/aot/support/ir_utils.py
- iree/turbine/transforms/general/rename_parameters.py
- iree/turbine/transforms/quantization/mm_group_quant.py
- tests/aot/api_test.py
- tests/aot/globals_test.py
- tests/aot/params_test.py
- tests/runtime/launch_test.py
- tests/transforms/general/rename_parameters_test.py
Frontends should not emit stream.parameter.named since https://github.com/iree-org/iree/pull/17303#issuecomment-2099354883
> [aot] Use flow.parameter.named instead of stream.parameter.named

- iree/turbine/kernel/boo/README.md
- add link to `iree-turbine` install instructions
- move env var doc to the bottom, since it's more for advanced usage/developers
> [boo] Add turbine install instructions to README

- iree/turbine/kernel/boo/op_exports/conv.py
- iree/turbine/kernel/boo/ops/conv.py
- iree/turbine/kernel/boo/ops/layout_customizable_conv.py
- tests/kernel/boo/op_exports/conv_backward_impl_test.py
This is to enable:
1. testing torch-compile route properly in the boo driver for backward conv
2. eventually enable combined backward modes
The slight downside of this change is that we may need to export an unused tensor for single-grad backward computations, but for real models, this will hopefully be a beneficial change since we can eventually combine both WRW and BWD kernels into a single vmfb.
> [BOO] Canonicalize `use_custom=False` module impls for backward conv

- iree/turbine/kernel/boo/driver/driver.py
- iree/turbine/kernel/boo/driver/preload.py
- iree/turbine/kernel/boo/driver/utils.py
- iree/turbine/kernel/boo/exports/parser.py
Don't ignore failure to parse certain arguments in the op-specific parser, report them instead. This may help cathing misspelled or otherwise incorrect arguments being passed to the driver. This parser runs last so all other arguments must have been consumed already.
> [boo] report unknown op-specific arguments

- iree/turbine/kernel/boo/op_exports/layer_norm.py
- tests/kernel/boo/op_exports/layer_norm_backward_impl_test.py
Add an op export for combined computaiton of all gradients in layer norm. This may be more efficient than executing them one by one in some cases and requires separate testing.
> [boo] add a combined backward layer norm

- iree/turbine/kernel/boo/runtime/launch.py
This flag is applied together with https://github.com/iree-org/iree/pull/22100 to transpose the convolution filter layout for input backward convolutions.
> [BOO] Add flag to run transpose filter preprocessing pipeline

- iree/turbine/kernel/boo/runtime/tuning_specs.mlir
Improves performance on the following configs on MI300X:
```
convbfp16 -n 1 -c 448 -H 118 -W 182 -k 448 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 8 -F 2 -t 1               -13.66 (-13.7%) 100.04 => 86.38
convbfp16 -n 1 -c 224 -H 235 -W 363 -k 224 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 4 -F 2 -t 1               -31.24 (-17.8%) 175.81 => 144.57
convbfp16 -n 1 -c 224 -H 470 -W 725 -k 224 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 4 -F 1 -t 1               -28.59 (-13.5%) 211.09 => 182.50
convbfp16 -n 1 -c 224 -H 235 -W 363 -k 224 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC …
```
> Update tuning spec

- iree/turbine/kernel/boo/driver/driver.py
This resolves OOM issues I've been hitting when doing large benchmarking runs, by clearing IREE's allocation cache. The HIP backend keeps a cache of allocations, and never frees entries in the cache. If a program continuously allocates memory of different sizes (like our driver does when benchmarking different configs), it'll eventually run out of memory.
A longer term fix would be to disable IREE's async caching in turbine, but that currently causes performance regressions.
> [boo driver] Trim allocations between benchmark runs
