iree-org/iree-turbine

- iree-requirements.txt
- pytorch-rocm-requirements.txt
- requirements.txt
Also as this is the first dev commit post 2.3, update some min versions.
> Bump IREE to 20240427.876.

- iree-requirements.txt
Update iree-requirements.txt to account for the new [llvm-project integrate](https://github.com/llvm/torch-mlir/commit/bce800a3f4200f8a28e844a91c2be2d2ce71c174).
> Bump IREE to 20240514.893

- shark_turbine/runtime/op_reg/base.py
- shark_turbine/transforms/general/custom_op_expansion.py
Signed-off-by: Stella Laurenzo <slaurenz@amd.com>
> Enable integer attributes and integer list attribute arguments in CustomOps

- .github/workflows/ci.yaml
- .github/workflows/test_build_release.yml
- MANIFEST.in
- build_tools/build_release.py
- build_tools/post_build_release_test.sh
- build_tools/post_pypi_release_test.sh
- iree-requirements.txt
- requirements.txt
- setup.py
- shark_turbine/dynamo/executor.py
- shark_turbine/dynamo/tensor.py
- shark_turbine/kernel/__init__.py
- shark_turbine/kernel/lang/__init__.py
- shark_turbine/ops/__init__.py
- tests/dynamo/importer_basic_test.py
- version_info.json
This commit makes the necessary changes to get out a successful release that passes all tests.
Also added some scripts to help with release validation.
New build release CI to make sure no commits break iree-turbine release build.
> Changes required for a successful build that passes tests 

- lit_tests/kernel/wave/promotion.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/address_spaces.py
- shark_turbine/kernel/wave/hoisting.py
- shark_turbine/kernel/wave/promotion.py
This PR adds patterns to promote global memory
reads to shared memory reads. Also adds a pattern
to hoist allocation nodes outside of reduction nodes.
> Add shared memory promotion patterns

- shark_turbine/support/conversions.py
- shark_turbine/support/ir_imports.py
> adds one of the fp8 datatypes to the importer

- shark_turbine/kernel/compiler/vector_codegen.py
This PR specifies the in_bounds attribute for vector.transfer_reads.
> Fix broken unit tests

- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/promotion.py
- shark_turbine/kernel/lang/global_symbols.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/address_spaces.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/distribution_symbols.py
- shark_turbine/kernel/wave/hoisting.py
- shark_turbine/kernel/wave/promotion.py
This PR adds a dollar prefix to all private globals to avoid namespace collisions with user defined
variables.
> Move globals to separate file and prefix with $

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/constraints_test.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds wave constraints which specify how to distribute a tensor dimension among waves. The assumption is that the dimension has already been distributed among workgroups and is further being distributed among waves.
> Add wave contraints

- shark_turbine/aot/exporter.py
In the context of a multi-device program this argument does not make sense. It has also been recently deprecated in IREE.
> Make target backends optional in ExportOutput::compile

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/tracing.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/promotion.py
- shark_turbine/kernel/wave/register_analysis.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds lowerings for reduction operators.
With these, we now have a complete GEMM lowering
that can be tested for correctness and benchmarked for performance.
> Add lowerings for reduction

- shark_turbine/kernel/compiler/kernel_codegen.py
- shark_turbine/kernel/wave/wave.py
- test.py
- tests/kernel/wave/wave_e2e_test.py
* Add basic infra to run kernels e2e (`TestLaunchContext` `run=True` argument)
* Add simple copy kernel as test (currently fails, 16 first values are correct and the rest are garbage, will debug it separately)
* To run e2e tests `WAVE_RUN_E2E_TESTS=1 pytest tests/kernel/wave/wave_e2e_test.py`
> [TK] Basic end-to-end infra

- tests/kernel/wave/wave_e2e_test.py
With some trial and error found some constraints configuration which gives correct result, but I have no idea what I'm doing. @harsh-nod please take a look.
> [TK] Fix e2e copy test

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/compiler/dispatch_codegen.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/utils.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_e2e_test.py
Implements expansion and distribution to workgroup, S.T they will take into account the number of threads in a workgroup/block. Additionally, we also add some support for symbolic vector_shape in HW constraints. Also incorporated some of @Hardcode84 's finding to fix the e2e copy test.
> [TKW] Implement workgroup expansion and execution support.

- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/wave/promotion.py
- shark_turbine/kernel/wave/utils.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds a generate_iree_ref test utility function that can be used to compare the outputs of tkw with iree. We also update the parameters of the gemm test and use generate_iree_ref to generate iree reference gemm outputs.
> Get e2e gemm functional

- build_tools/post_build_release_test.sh
- iree-requirements.txt
We can remove the pinned iree now that the import issue was resolved in iree
> Unpin iree

- shark_turbine/kernel/wave/scheduling/graph_utils.py
- shark_turbine/kernel/wave/scheduling/modulo_scheduling.py
- tests/kernel/wave/scheduling_test.py
This PR adds utils to find strongly connected components and simple cycles in directed graphs. These are required for implementing modulo scheduling.
> Add graph utils for modulo scheduling

- shark_turbine/kernel/ops/wave_ops.py
- shark_turbine/kernel/wave/expansion.py
- shark_turbine/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/wave/promotion.py
- shark_turbine/kernel/wave/utils.py
- shark_turbine/kernel/wave/wave.py
* Change `Read` return type from from `Memory` to `Register` and make it respect mapping shape. 
* Add `memory_type` property to get the original mem type
* Update related passes
* Some smaller fixes:
* `_contains` func to properly handle case when input is `None`
* `safe_subs` to properly handle case when input is not a sympy expr (e.g. when `address_space` has explicit value set instead of sympy placeholder)
* `custom.axis.name` -> `str(custom.axis)` to handle cases when axis is expr and not just a symbol
> [TKW] Read type fixes

- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/wave/minimize_global_loads.py
This PR fixes a bug in the index computation for
minimizing global loads. The index should load multiple elements only from the contiguous dimension.
> Fix bug in indexing

- shark_turbine/kernel/wave/docs/gemm_example.md
This PR adds documentation describing
how to implement GEMMs in tkw and in the
process explains the different primitives
and concepts in tkw.
> Add documentation for GEMM example

- shark_turbine/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
e2e igemm conv finally working.
Python lambdas capture values by name, which cause wrong value to be used if variable was changed later.
> [TKW] e2e igemm

- iree-requirements-ci.txt
ci(iree): update version
to release 20240918.1020
This update is required for another PR https://github.com/iree-org/iree-turbine/pull/123
> Update iree-requirements-ci.txt to 20240918.1020

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/wave/utils.py
This PR adds an LICM pass to hoist loop invariant
code outside of loops.
> Add LICM pass to canonicalize function

- lit_tests/kernel/wave/codegen.py
- shark_turbine/kernel/wave/codegen.py
- shark_turbine/kernel/wave/constraints.py
- shark_turbine/kernel/wave/wave.py
- tests/kernel/wave/constraints_test.py
- tests/kernel/wave/wave_e2e_test.py
Add support for cases when input sizes are not divisible by WG sizes, use masked vector instructions int his case, to only access elements within arrays bounds.
> [TKW] Masking

- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/minimize_global_loads.py
- shark_turbine/kernel/wave/barriers.py
We move to an extremely simple barrier insertion
strategy as a baseline. While suboptimal, this
should provide a good reference when transitioning to more advance barrier insertion approaches.
> Simplify barrier insertion strategy

- tests/kernel/wave/wave_e2e_test.py
- tests/kernel/wave/wave_gemm_test.py
We would like this to be controlled with a flag.
> Disable benchmarking on all e2e tests for now

- mypy.ini
- shark_turbine/tools/interpreter.py
* Add `arith.andi`, `arith.cmpi`, `vector.maskedload`, `vector.gather`, `vector.contant_mask`, `vector.insertelement`, `vectot.splat`, support non-splatted contants.
* Add `interpret_ndrange` helper
> [TKW] Update IR interpreter

- iree/turbine/kernel/wave/docs/mlsys/tkw.bib
- iree/turbine/kernel/wave/docs/mlsys/tkw.tex
Adds preliminary tikz overview figure and an initial description of the fx tracing process
> Add preliminary tikz overview figure 

- iree/turbine/kernel/wave/docs/mlsys/tkw.tex
This also adds lots of notes, todos and general structure
> [tkw] Progress on compiler description

- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/codegen.py
Index calculations should never overflow. Add corresponding flags to `arith.addi/muli`.
> [TKW] Add overflow flags to index calculations

- examples/resnet-18/README.md
- examples/resnet-18/requirements.txt
- examples/resnet-18/resnet-18.py
Tested locally on Linux. Still works :D
> Rebase examples/resnet-18 on latest published packages.

- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/wave_attention_test.py
This PR adds a new attention shape and modifies
the tile sizes for better performance.
It also fixes a bug in the offset calculation where the offset could be larger than the number of
partitions.
> Add more attention shapes

- iree/turbine/kernel/wave/scheduling/graph_utils.py
- iree/turbine/kernel/wave/scheduling/modulo_scheduling.py
- tests/kernel/wave/scheduling_test.py
This PR address comments from the last commit
regarding reducing the overhead of instantiating a pool of works at every iteration.
> Cleanup of APLP code

- version_info.json
Just published version 3.0.0: https://pypi.org/project/iree-turbine/3.0.0/. IREE release tracker: https://github.com/iree-org/iree/issues/19063.
> Bump version to 3.1.0 after releasing 3.0.0.

- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/compiler/utils.py
- iree/turbine/kernel/wave/codegen.py
- lit_tests/kernel/wave/attention.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_attention_test.py
This PR adds support for dynamic attenton dims
for attention (except K1).
> Add dynamic attention

- lit_tests/kernel/wave/codegen.py
`CHECK-LABEL` prevents matching IR from unrelated tests.
> [NFC][TKW] Use CHECK-LABEL in codegen lit tests

- tests/kernel/wave/wave_e2e_test.py
Merges best IGEMM variant from opt branch.
> [TKW] IGEMM conv merge

- iree/turbine/kernel/_support/indexing.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
Always print full form with sizes/strides to avoid ambiguity/confusion with sympy expr printing.
> [TKW][NFC] Change IndexSequence print format

- iree/turbine/kernel/wave/promotion.py
- lit_tests/kernel/wave/attention.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/promotion.py
- tests/kernel/wave/wave_attention_test.py
This PR adds a sample implementation of attention
during the decode step. This does not include a
kv cache.
> Add attention decode kernel

- README.md
* Mention new nightly releases in install instructions
* Reword PyTorch install instructions
* Remove dead links
* Add new hyperlinks to some terms
* Add link to iree.dev documentation
* Resize giant header image
* Fix some indentation under ordered lists
> [docs] Refresh README documentation.

- iree/turbine/kernel/wave/utils.py
This PR uses sympy CSE and integral assumptions
to simplify complex expressions.
> Simplify contiguity computation

- iree/turbine/aot/support/ir_utils.py
Change from attr name from `iree.abi.affinity` to `stream.affinity`
> Fix name for stream affinity

- .github/workflows/ci-tk.yaml
- .github/workflows/ci.yaml
This will let us test the workflows without needing to push changes.
> Add workflow_dispatch triggers to ci.yml and ci-tk.yml.

- tests/kernel/wave/attention/chained_gemm_test.py
- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/evoformer_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/common/shapes.py
- tests/kernel/wave/common/utils.py
This PR creates a common utils directory for
e2e test functions and shapes and splits the
attention tests into multiple files.
> Refactor attention e2e tests

- version.json
Just published version 3.1.0:
* https://pypi.org/project/iree-turbine/3.1.0/
* https://github.com/iree-org/iree-turbine/releases/tag/v3.1.0
IREE release tracker: https://github.com/iree-org/iree/issues/19192.
> Bump version to 3.2.0 after releasing 3.1.0.

- iree/turbine/ops/iree.py
Operation is used to handle adjacent to transfers to prevent unwanted fusions.
> Add `barrier_on_logical_device` for synchronizations

- iree/turbine/kernel/compiler/kernel_codegen.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/type_inference.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
Simple conditional op which is lowered to `scf.if` (without else for now). Expected argument of integer type and treats it as:
```
scf.if(%val != 0) {
...
}
```
> [TKW] `tkw.conditional` op

- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/wave_sim_test.py
This reverts commit e226606631c442aa9170309722d19b170ecbb494.
> Revert "Replace deprecated `assert_allclose` (#405)"

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/expansion/expansion_utils.py
- iree/turbine/kernel/wave/promotion.py
- iree/turbine/kernel/wave/templates/attention_common.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention.py
- tests/kernel/wave/attention/extend_attention_test.py
This PR adds support for extend attention (also known as chunked prefill).  A new kernel template is added along with an end to end test with a reference kernel.
> Add extend attention

- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
This PR adds a causal option to extend attention.
Also adds a lit test and updates the e2e test to test with is_causal=True.
> [Wave] Add causal option to extend attention

- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- Fix error for creating cur_cache_dir
- Hardcode data casting for SGLang e2e testing
> Fixes for SGLang E2E testing

- version.json
See the 3.2.0 release tracker at https://github.com/iree-org/iree/issues/19641 and published release at https://github.com/iree-org/iree-turbine/releases/tag/v3.2.0.
> Bump version to 3.3.0 after releasing 3.2.0.

- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/utils.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
This PR adds support for the 32 x 32 x 8 MFMA intrinsic in extend attention.
> [Wave] Get extend working with more MFMA intrinsics

- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
To match optimizations done in sglang triton kernel, we added:
1. Causal mask optimization, to not do redundant work where masks are all zeroes anyways
2. Setting BLOCK_D_KV to just be D_KV
> [Wave] Various extend attention optimization

- iree/turbine/kernel/wave/codegen/read_write.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/evoformer.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/attention/prefill_attention.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/igemm.py
* Manually unroll gathers/scatters into 1-element masked ops.
> [TKW] Unroll gathers/scatters

- iree/turbine/kernel/wave/constraints.py
- iree/turbine/kernel/wave/index_sequence_analysis.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
The call to HardwareConstraint.apply is unnecessarily convoluted.
> [NFC] Better HardwareConstraint.apply APIs

- iree/turbine/kernel/wave/templates/extend_attention.py
This PR implements a empirically determined heuristic to determine the tile size when one is not explicitly provided by the user.
> [Wave] Use a heuristic to pick the tile sizes for extend

- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- iree/turbine/kernel/wave/analysis/partition_strided_operators.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/scheduling.py
- tests/kernel/wave/scheduling_test.py
- tests/kernel/wave/visualization_test.py
This PR splits the index sequence analysis code into two separate files, one for partition strided operators and the other for index sequence analysis.
> [Wave] Split index sequence analysis

- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/templates/vanilla_attention.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/runtime/cache_test.py
Adds non-transposed V Attention kernel variant and test
> [Wave] Add non-transposed V Attention kernel variant

- iree/turbine/kernel/_support/indexing.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/codegen/read_write.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/codegen.py
Use sympy expression instead of constructing arith ops directly.
> [TKW] Self index refactoring

- iree/turbine/kernel/wave/cache.py
- iree/turbine/kernel/wave/utils.py
- iree/turbine/kernel/wave/wave.py
This PR fixes an erroneous assumption made by the previous PR that when using the wave runtime the grid is always constant. Instead, we use sympy to generate a lambda (and lambda str when caching the kernel) that can be used to determine the grid prior to launching the kernel.
> [Wave] Compute grid before kernel launch

- version.json
Release tracker: https://github.com/iree-org/iree/issues/19960
> Bump version to 3.4.0 after 3.3.0 release.

- iree/turbine/kernel/wave/templates/extend_attention.py
- iree/turbine/kernel/wave/templates/extend_attention_rpe.py
- lit_tests/kernel/wave/attention/extend_attention.py
- tests/kernel/wave/attention/extend_attention_test.py
Update extend attention to use flattened prefill indices
> [Wave] Update extend attention kernel signature

- iree/turbine/kernel/wave/templates/quantized_attention.py
- lit_tests/kernel/wave/attention/quantized_attention.py
- tests/kernel/wave/attention/quantized_attention_test.py
- tests/kernel/wave/common/shapes.py
This PR introduce a Wave FP8 attention that follows the quantization scheme currently used in IREE and Brevitas
> [Wave] Implement FP8 Quantized attention

- iree/turbine/kernel/compiler/ir.py
- iree/turbine/kernel/wave/codegen/emitter.py
- lit_tests/kernel/wave/attention/decode_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/gemm.py
- lit_tests/kernel/wave/mma.py
- tests/tools/interpreter_test.py
* Add ability to use `affine.apply` for index codegen
* Limited to non-vector index type for now, need https://github.com/llvm/llvm-project/pull/129442 for vector support
> [TKW] Use affine apply

- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/codegen/read_write.py
- iree/turbine/kernel/wave/compile_options.py
This PR adds an option to enable fast math for unary and binary floating point operations.
> [Wave] Add fast math option

- iree/turbine/kernel/wave/templates/gqa_vanilla_attention.py
This PR guards the FP8 parts of the kernel with the use_fp8 flag and adds a cast in case the output dtype is not the same as the input dtype.
> [Wave] Fix issues in bshd gqa kernel

- tests/kernel/boo/ops/boo_conv_test.py
> [BOO] temporarily xfail bias grad-check test

- iree/turbine/kernel/wave/cache.py
- tests/kernel/wave/runtime/cache_test.py
- Actually use the subfunctions to do the hashing aside (this overall fixes changing freevar in nested fn)
however brought up/exposed some other issues
- Hoist out function/subfunction related keys to outside the loop
- Use list to track subfunctions because set generates non-deterministic hashes
- error handling when fn.\_\_closure__ == None.
> [Wave] Improve WaveCacher to handle changing freevar in nested fn.

- iree/turbine/kernel/wave/layers/quant_attention.py
- iree/turbine/kernel/wave/templates/quantized_attention.py
- tests/kernel/wave/layers/wave_quant_attention_test.py
Implement a quantized FP8 attention function that can take in any Bx{B0 x B1 x .. BN} x S x D layout FP8 attention through flattening and unflattening of batch size. This PR also made sure that the batch, query_seq_len and kv_seq_len is dynamic S.T we can ensure minimal recompiles.
> [Wave] Implement efficient and user friendly FP8 SDPA Op

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/templates/extend_attention.py
- lit_tests/kernel/wave/attention/extend_attention.py
- lit_tests/kernel/wave/codegen.py
Add tanh approximation for extend attention, bring 15% kernel improvement.
> [WAVE] Tanh approximation flashinfer implementation

- iree/turbine/kernel/_support/tracing.py
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/barriers.py
- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/minimize_global_loads.py
- iree/turbine/kernel/wave/type_inference.py
- lit_tests/kernel/wave/iteration.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds fixes to enable iterating over dimensions without any loop carried variables. A sequential batched gemm example is added.
> [Wave] Enhancements to iterate over a dimension without any loop carried variables

- iree/turbine/kernel/boo/conv_exports/README.md
I'm adding the build instruction from lesson learned building and running boo driver. This PR is NFC and changes readme only.
> [BOO] Adding more build and triage details to boo driver readme

- iree/turbine/kernel/wave/templates/speculative_decoding.py
- tests/kernel/wave/speculative_decode_test.py
This PR from Son adds a reference PyTorch kernel that implements tree speculative sampling.
> Speculative Decoding in PyTorch 

- lit_tests/kernel/wave/codegen.py
This PR fixes the lit test missing a compile to mlir flag.
> Fix lit test on main

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/decompose_reduce_ops.py
- iree/turbine/kernel/wave/decompose_scan_ops.py
- iree/turbine/kernel/wave/utils/classes.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_e2e_test.py
- Implement different shuffleMode for ShuffleOp with enums + mapping
- Use gpu shuffle up on scanOp to enable unaligned shapes
> [Wave] Implement different shuffleMode + Handle unaligned Scan

- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/templates/speculative_decoding.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/speculative_decode_test.py
- Fix bugs and add test for float cmps
- Fix bug and add test for RegisterOp when symbol is not same type as vector type/Register type
- Implement "lower" speculative decoding kernel in Wave
> [Wave] Implement CDF and spec dec lower kernel in Wave

- tests/kernel/wave/runtime/cache_test.py
> [Wave] Add scaling to reference kernel in cache test

- iree/turbine/kernel/compiler/dispatch_codegen.py
- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- tests/kernel/wave/attention/paged_attention_test.py
Similar to extend attention changes
> [TKW] Update paged decode API

- lit_tests/kernel/wave/codegen.py
- lit_tests/kernel/wave/gemm.py
This PR fixes missing colons and incorrect
CHECK statements in the lit tests.
> [Wave] Fix broken lit tests

- iree/turbine/kernel/boo/conv_exports/launch.py
In case a certain configuration is taking more than 10 seconds to compile, I'd like the jit callback to fail.
Any single kernel taking more than 10 seconds to compile should be considered a compiler bug (regardless of whether the kernel does eventually compile successfully), so we should mark that as a failure when running `boo_driver.py` or `preload.py`.
Although the long compile times I was seeing seem to get fixed by doing a fresh iree build, I think this functionality should be introduced regardless.
> [BOO] Add a timeout for out-of-process compilation

- examples/jupyter/wave_gemm_example.ipynb
This PR adds a simple notebook showing how to do a mixed precision transposed GEMM in Wave.
> [Wave] Add jupyter notebook showing how to do a GEMM

- iree/turbine/kernel/wave/templates/paged_decode_attention.py
sglang decode numbers on large shapes `seq_len=100, (32, 128, 2, 512, 512)`:
```
phase_0: 77-> 35
phase_1: 38 -> 19
```
> [TKW] Tweak Paged Decode kernel waves/tile sizes

- iree/turbine/kernel/wave/utils/print_utils.py
This PR adds the ability to print fx.graphs in a manner similar to mlir graphs, with the caveat that not all the information about the fx.nodes is printed yet.
> [Wave] Add mlir style printing

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/analysis/index_sequence_analysis.py
- iree/turbine/kernel/wave/codegen/handlers.py
- iree/turbine/kernel/wave/utils/graph_utils.py
- lit_tests/kernel/wave/codegen.py
- Implement missing scheduling ops such as s_barrier and set_prio
- Made changes to index sequence analysis so can be exposed to users.
> [Wave] Add scheduling/synchronization related ops

- iree/turbine/kernel/wave/compile_options.py
- iree/turbine/kernel/wave/utils/print_utils.py
- iree/turbine/kernel/wave/wave.py
Add compiler option to print Wave pass timings.
> [TKW] Option to print pass timings

- docs/wave/pingpong_reordering.rst
- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/expansion/expansion.py
- iree/turbine/kernel/wave/schedule_reordering.py
- iree/turbine/kernel/wave/scheduling/loop_reconstruction.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/gemm.py
- tests/kernel/wave/wave_gemm_test.py
Documentation and comment to be  written..
> [Wave] Two PP cluster GEMM

- .github/workflows/ci-tk.yaml
- .github/workflows/test_build_release.yml
- build_tools/post_build_release_test.sh
- docs/wave/aplp.rst
- docs/wave/getting_started.rst
- iree/turbine/kernel/wave/scheduling/aplp/Cargo.toml
- iree/turbine/kernel/wave/scheduling/aplp/pyproject.toml
- iree/turbine/kernel/wave/scheduling/aplp/src/lib.rs
- iree/turbine/kernel/wave/scheduling/aplp/src/prune.rs
- iree/turbine/kernel/wave/scheduling/graph_utils.py
- iree/turbine/kernel/wave/scheduling/modulo_scheduling.py
- requirements.txt
This PR adds an implementation of APLP
for software pipelining in Rust to speed up
the scheduling computation.
> [Wave] Make APLP faster

- iree/turbine/kernel/boo/conv_exports/tuning_specs.mlir
Add tuning configs for the following configurations:
```
convbfp16 -n 16 -c 2 -H 450 -W 450 -k 2 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -t 1 -b 0 -F 1
convbfp16 -n 16 -c 64 -H 225 -W 225 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -t 1 -b 0 -F 1
convbfp16 -n 16 -c 64 -H 225 -W 225 -k 64 -y 1 -x 3 -p 0 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -t 1 -b 0 -F 1
convbfp16 -n 16 -c 768 -H 48 -W 32 -k 2048 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -t 1 -b 0 -F 1
convbfp16 -n 16 -c 16 -H 225 -W 225 -k 64 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 --in_layout NHWC --fil_layout NHWC …
```
> [boo] More tuning configurations

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- lit_tests/kernel/wave/codegen.py
Added a Binary operation for computing atan2. Test added to lit_tests/kernel/wave/codegen.py
> [Wave] Added atan2 operation

- iree/turbine/kernel/wave/templates/speculative_decoding.py
- Fixes `uniform_sampling` dimensions
- Default predict token to n-1 from vocabulary
> [Wave] Speculative decode - default predict token to last token in vocab

- iree/turbine/kernel/wave/utils/general_utils.py
- iree/turbine/kernel/wave/utils/run_utils.py
- iree/turbine/kernel/wave/wave.py
- requirements-iree-pinned.txt
- tests/kernel/wave/wave_e2e_test.py
See https://github.com/iree-org/iree/issues/20849 and https://github.com/iree-org/iree/pull/20988
> Update IREE version, remove dlpack hack and add tensor leak test

- .github/workflows/ci.yaml
- tests/runtime/device_stream_test.py
Partly addresses <https://github.com/iree-org/iree-turbine/issues/895>, but we should still add some more iree/pytorch interop tests.
> Add a python3.11 mi300 unit tests and type checking job

- .gitignore
ignore all cargo related files
> [Wave] Add aplp to gitignore

- iree/turbine/kernel/boo/conv_exports/boo_driver.py
1. Looks for multiple available GPUs and distributes the work across all of them. I'm not sure if this is always desirable, so we could add another command-line arg for toggling this.
2. Synchronizes all devices and collects garbage at reasonable points. I chose to clean up after generating 96GB worth of output tensors. Some of these outputs may already get cleaned up, but half the memory available for an Mi300x (192 GB) seems like a very safe threshold to collect at.
> [BOO] Add some boo_driver improvements

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/read_write.py
- iree/turbine/kernel/wave/generate_bounds_exprs.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/barriers.py
- lit_tests/kernel/wave/expansion.py
- lit_tests/kernel/wave/index_sequence_analysis.py
- lit_tests/kernel/wave/minimize_global_loads.py
- lit_tests/kernel/wave/promotion.py
- lit_tests/kernel/wave/tracing.py
* Move masking/bounds expressions generation from lowering to dedicated pass
* No functional changes
> [Wave] Mask/Bounds generation refactoring

- docs/wave/schedule.rst
- iree/turbine/kernel/wave/compile_options.py
- iree/turbine/kernel/wave/memory_analysis/minimize_shared_allocs.py
- iree/turbine/kernel/wave/scheduling/resources.py
- iree/turbine/kernel/wave/scheduling/schedule.py
- iree/turbine/kernel/wave/templates/gemm.py
- iree/turbine/kernel/wave/utils/graph_utils.py
- iree/turbine/kernel/wave/utils/print_utils.py
- iree/turbine/kernel/wave/wave.py
- tests/kernel/wave/wave_gemm_test.py
This PR adds the ability to dump the generated schedule
and import a hand modified schedule. No verification
is done on the imported schedule.
> [Wave] Add ability to export and import schedules

- iree/turbine/kernel/ops/wave_ops.py
- iree/turbine/kernel/wave/codegen/handlers.py
- lit_tests/kernel/wave/codegen.py
> [Wave] Add `sqrt` op

- iree/turbine/kernel/wave/templates/paged_decode_attention.py
- tests/kernel/wave/attention/paged_attention_test.py
Refactor temp array shape to separate function so we won't need to update all users if we decide to transpose it later.
> [Wave] Paged decode temp arrays shape helper

- .github/workflows/ci-tk.yaml
- iree/turbine/kernel/compiler/ir.py
- iree/turbine/kernel/wave/compile.py
- iree/turbine/kernel/wave/compile_options.py
- iree/turbine/kernel/wave/water.py
- lit_tests/kernel/wave/water.py
- lit_tests/lit.cfg.py
Introduce a minimalist connection between Wave kernels and C++ opt-style tool performing a out-of-bounds access checks using dataflow analyses. The tool is expected to be precompiled and installed on the system.
> Proof-of-life connection between Wave and a C++ opt tool

- iree/turbine/kernel/wave/codegen/emitter.py
- iree/turbine/kernel/wave/wave.py
- lit_tests/kernel/wave/codegen.py
It way help integer range analysis later.
> [Wave] Set GPU ID ops upper bounds

- iree/turbine/ops/iree.py
- iree/turbine/runtime/op_reg/base.py
- iree/turbine/runtime/op_reg/eager.py
- iree/turbine/transforms/general/custom_op_expansion.py
I was confused about a few things first time reading this code. I added to the comments so hopefully the next person can understand things a little faster.
> [NFC] Update a few comments

- iree/turbine/kernel/boo/runtime/launch.py
I was pretty confused what actually happened under the hood when doing something like the following.
```python
import torch
from iree.turbine.kernel.boo.runtime import get_launchable
class SimpleMatmul(torch.nn.Module):
def forward(self, x, w):
return torch.matmul(x,w)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
x_shape = ...
w_shape = ...
gen = torch.Generator(device=device)
gen.manual_seed(10)
x0 = torch.randn(x_shape, generator=gen, device=device)
w0 = torch.randn(w_shape, generator=gen, device=device)
launchable = get_launchable(SimpleMatmul, (x0, w0), func_name="sample_boo_matmul", force_single_dispatch=True)
```
This PR adds a rough map of what happens below to `get_module_asm`.  May this be a guide to the next person spelunking through code gen!
> [NFC] Add comment for `get_module_asm`

- tests/conftest.py
- tests/kernel/wave/attention/alibi_attention_test.py
- tests/kernel/wave/attention/backward_attention_test.py
- tests/kernel/wave/attention/decode_attention_test.py
- tests/kernel/wave/attention/evoformer_test.py
- tests/kernel/wave/attention/extend_attention_test.py
- tests/kernel/wave/attention/paged_attention_test.py
- tests/kernel/wave/attention/prefill_attention_test.py
- tests/kernel/wave/attention/quantized_attention_test.py
- tests/kernel/wave/attention/t5_rpe_attention_test.py
- tests/kernel/wave/attention/vanilla_attention_test.py
- tests/kernel/wave/nn/functional/wave_quant_attention_test.py
- tests/kernel/wave/nn/functional/wave_sdpa_test.py
- tests/kernel/wave/runtime/cache_test.py
- tests/kernel/wave/speculative_decode_test.py
- tests/kernel/wave/wave_gemm_test.py
To make tests more reproducible.
> Seed torch before each test

- iree/turbine/kernel/wave/codegen/read_write.py
- iree/turbine/kernel/wave/compile_options.py
- lit_tests/kernel/wave/codegen.py
- tests/kernel/wave/wave_gemm_test.py
Replaced buffer loads and stores with stride-aware buffer loads and stores using fat_raw_buffer_casts.
> [Wave] Fixing Correctness of Buffer Loads/Stores and Replaced Buffer Operations with Unmasked Vector Loads/Stores on FatRawBufferCast"ed" Pointers

- version.json
Release tracker: iree-org/iree#21457
> Bump version to 3.7.0 after 3.6.0 release.

- iree/turbine/kernel/boo/op_exports/gemm.py
- `List` and `Union` are deprecated since 3.9
- add some missing type annotations
> [boo] clean up, modernize types in gemm

- iree/turbine/kernel/boo/runtime/tuning_specs.mlir
This is a full re-run of tuning for forward convs. The following configs have over a 1.5x speedup over un-tuned:
```
convbfp16 -n 16 -c 96 -H 24 -W 16 -k 96 -y 3 -x 1 -p 2 -q 0 -u 1 -v 1 -l 2 -j 2 -m conv -g 1 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100
convbfp16 -n 16 -c 288 -H 24 -W 16 -k 288 -y 3 -x 1 -p 1 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 3 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100
convbfp16 -n 16 -c 96 -H 24 -W 16 -k 96 -y 3 -x 1 -p 4 -q 0 -u 1 -v 1 -l 4 -j 4 -m conv -g 1 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100
convbfp16 -n 16 -c 48 -H 96 -W 64 -k 48 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 100
convbfp16 -n …
```
> [boo] Update tuning spec

- iree/turbine/kernel/boo/runtime/cache.py
- tests/kernel/boo/conftest.py
- tests/kernel/boo/fusion/integration_test.py
- tests/kernel/boo/fusion/subgraph_fusion_test.py
- tests/kernel/boo/modeling/boo_conv_module_test.py
- tests/kernel/boo/ops/boo_conv_aot_test.py
- tests/kernel/boo/ops/boo_conv_test.py
- tests/kernel/boo/ops/graph_ops_test.py
This avoids interference between tests.
> [boo] Automatically reset caches between tests

- iree/turbine/runtime/device.py
Supplying a specific SKU will allow IREE to optimize for specific target details.
This is implemented as a table mapping torch device names to IREE SKU strings. For now I've included the known Instinct devices listed here:
https://github.com/iree-org/iree/blob/66b2f337c8019abf4716487ad32adea032afbb81/compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/KnownTargets.cpp#L425-L440
Unfortunately this requires keeping the table in sync with IREE as new targets are added.
> [device] Use SKU as HIP target when possible

- iree/turbine/kernel/boo/ops/graph.py
- iree/turbine/kernel/boo/ops/utils.py
When a conv output has all unit spatial dims, it is in both contiguous format and channels last format. There was an inconsistency between the generation of the graph op inferring the memory format from the `TensorMetadata`, and the conv replacement tool inferring the layout from the fake tensor.
Unfortunately, this change can't easily be tested, since pytorch/miopen seems to unreliably select whether to return channels last or contiguous outputs for conv.
> [BOO] Don't use `TensorMetadata` to infer output layouts
